<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
include_once  "/ckeditor/ckeditor.php";

// Create a class instance.
$CKEditor = new CKEditor();

// Path to the CKEditor directory.
$CKEditor->basePath = $this->baseUrl().'/ckeditor/';

// Replace a textarea element with an id (or name) of "textarea_id".
?>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#help").validationEngine();
            });
  </script>
<p>&nbsp;</p>
<form method="post" action="" id="help">
<input type="hidden" name="id" value="<?php echo $this->SpDtd['id'];?>"/>
<table width="75%" border="0" cellspacing="3" cellpadding="0" align="center">
  <tr>
    <td colspan="3" class="list-table-header">Update Speciality</td>
    </tr>
  <tr>
    <td class="label line">Speciality</td>
    <td class="label line">:</td>
    <td class="line"><input name="sp_name" type="text" id="sp_name" size="50" maxlength="50"  class="validate[required]" value="<?php echo $this->SpDtd['sp_name'];?>"/></td>
  </tr>
    <tr>
    <td class="label line">Listing Order</td>
    <td class="label line">:</td>
    <td class="line"><input name="listing_order" type="text" id="listing_order" size="50" maxlength="50"  class="validate[required]" value="<?php echo $this->SpDtd['listing_order'];?>"/></td>
  </tr>
  <tr>
    <td class="label line">Status</td>
    <td class="label line">:</td>
    <td class="label line" align="left">
     <label>
          <input name="sp_status" type="radio" value="1" <?php echo($this->SpDtd['status']==1)?'checked="checked"':"";?>/>
          Active</label>
        <label>
          <input type="radio" name="sp_status" value="0"  <?php echo($this->SpDtd['status']==0)?'checked="checked"':""?>/>
          Disable</label>
    </td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td><input type="submit" name="Submit" value="Update" /></td>
  </tr>
</table>
</form>
<?php 
$CKEditor->replace("contents");
?>