<?php //Do not edit this file by hand, it will be overwritting by the configuration utility. 
$TIMECARD_CONFIG['minimum_report_level'] = '5';
$TIMECARD_CONFIG['minimum_see_level'] = '5';
$TIMECARD_CONFIG['minimum_edit_level'] = '6';
$TIMECARD_CONFIG['integrate_with_helpdesk'] = '1';
$TIMECARD_CONFIG['show_possible_hours_worked'] = '1';
?> 
