<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
 <script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#planfeature").validationEngine();
            });
  </script>
<p>&nbsp;</p>
<form method="post" action="" id="planfeature">
<table width="75%" border="0" cellspacing="3" cellpadding="0" align="center">
  <tr>
    <td colspan="3" class="list-table-header">Add New Plan Feature </td>
    </tr>
  <tr>
    <td class="label line">Feature Caption </td>
    <td class="label line">:</td>
    <td class="line"><input name="hpcm_type_name" type="text" id="hpcm_type_name" size="60" maxlength="150"  class="validate[required]"/></td>
  </tr>
  <tr>
    <td class="label line">Sort Order </td>
    <td class="label line">:</td>
    <td class="line"><input name="hpcm_order" type="text" id="hpcm_order"  class="validate[required],custom[integer]"/></td>
  </tr>
  <tr>
    <td class="label line">Status</td>
    <td class="label line">:</td>
    <td class="labe line">
      <label class="label">
        <input name="status" type="radio" value="1" checked="checked" />
        Active</label>
      <br />
      <label class="label">
        <input type="radio" name="status" value="0" />
        Disable</label></td>
  </tr>
  <tr>
    <td align="left">This Feature is Primary or Secondary<br />
      (Primary feature cannot delete)</td>
    <td>:</td>
    <td><p>
      <label>
        <input name="delete" type="radio" id="delete_0" value="0" checked="checked" />
        Yes</label>
      <br />
      <label>
        <input type="radio" name="delete" value="1" id="delete_1" />
        No</label>
      <br />
    </p></td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td align="right">&nbsp;</td>
    <td>&nbsp;</td>
    <td><input type="submit" name="Submit" value="Add" /></td>
  </tr>
</table>
</form>