<?php
//$this->title="New Customer Add";
//$this->headTitle($this->title); // for title

?>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#userregister").validationEngine();
            });
	function checkoption(ival)
	{
		if(ival=="Other")
		{
			$("#other").css("visibility","visible");
				
		}
		else
		{
			$("#other").css("visibility","hidden");	
		}
	}
	function checkstate(ival)
	{
		if(ival=="USA")
		{
			$("#usastate").css("visibility","visible");
			$("#usastate").css("width","0px");
			$("#otherstate").css("visibility","hidden");
		}
		else
		{
			$("#usastate").css("visibility","hidden");	
			$("#otherstate").css("visibility","visible");
			$("#otherstate").css("margin","0");
		}
	}
  </script>
<?php 
//$this->Pre($this->formdata);
if($this->formdata['error']!="")
{
	echo '<table width="100%" border="0" cellspacing="0" cellpadding="0">';
	  echo '<tr>';
	    echo '<td><img src="'.$this->baseUrl().'/images/error.png" width="24" height="24" alt="Error" /></td>';

	    if($this->formdata['error']=="facility")
	    	echo '<td class="error">The facility Identifier name ('. $this->formdata['hf_facility_identifier'].') is alreay taken by another user. Please change the facility name</td>';
	    if($this->formdata['error']=="dashboarduser")
	    	echo '<td class="error">The Email Address ('. $this->formdata['hf_email'].') is alreay taken by another user. Please change Email</td>';
	  echo '</tr>';
	echo '</table>';
}
?>
<!-- form id="userregister" method="post" action="<?php echo $this->baseUrl();?>/UserRegister/userregister"-->
<form id="userregister" method="post" action="">
  <input type="hidden" name="_sec" value="register">
  <input type="hidden" name="apid" id="apid" value="<?php echo $this->plandetails['apid'];?>" />
  <input type="hidden" name="pid" id="pid" value="<?php echo $this->plandetails['pid'];?>" />
  <input type="hidden" name="bpcost" id="bpcost" value="<?php echo $this->plandetails['bpcost'];?>" />
  <input type="hidden" name="btotalfee" id="btotalfee" value="<?php echo $this->plandetails['btotalfee'];?>" />
  <input type="hidden" name="pcost" id="pcost" value="<?php echo $this->plandetails['pcost'];?>" />
  <input type="hidden" name="setupfee" id="setupfee" value="<?php echo $this->plandetails['setupfee'];?>" />
  <input type="hidden" name="totalfee" id="totalfee" value="<?php echo $this->plandetails['totalfee'];?>" />
  <?php 
  if($this->cms)
  {
  		echo '<div class="cms">';
		if(!$this->cms['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cms['cms_details'];
	echo '</div>';
  }
?>
  <table border="0" align="center" cellpadding="0" cellspacing="3">
    <tr>
      <td class="label-no">Organization Name</td>
      <td class="label-no">:</td>
      <td colspan="7"><input name="hf_organization" type="text" class="validate[required]" id="hf_organization" tabindex="1" value="<?php echo $this->formdata['hf_organization']?>" size="45" maxlength="150"/></td>
    </tr>
    <tr>
      <td class="label-no">Organization <br />
      short name</td>
      <td class="label-no">:</td>
      <td colspan="4"><input name="hf_facility_identifier" type="text" id="hf_facility_identifier" maxlength="150" class="validate[required],ajax[ajaxHostedIdentifier]" value="<?php echo $this->formdata['hf_facility_identifier']?>" tabindex="1"/> <?php $this->DisplayHelp('UserRegistrtion','FacilityIdentifier');?></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
     <tr>
       <td align="left" class="label-no">Suffix</td>
       <td align="left" class="label-no">:</td>
       <td colspan="7" align="left" class="label-no">
       <table border="0" align="left" cellpadding="0" cellspacing="0">
  <tr>
    <td><select name="hf_facility_suffix" tabindex="2">
      <option value="Dr." selected="selected">Dr.</option>
      <option value="Mr.">Mr.</option>
      <option value="Miss.">Miss.</option>
      <option value="Mrs.">Mrs.</option>
      <option value="Ms.">Ms.</option>
    </select></td>
    <td class="label-no">First Name</td>
    <td class="label-no">:</td>
    <td><input name="hf_facility_name" type="text" class="validate[required],custom[onlyLetterwithSpaceandAppostophy]" id="hf_facility_name" tabindex="3" value="<?php echo $this->formdata['hf_facility_name']?>" size="15" maxlength="150"/></td>
    <td class="label-no">Last Name</td>
    <td class="label-no">:</td>
    <td><input name="hf_facility_lname" type="text" class="validate[required],custom[onlyLetterwithSpaceandAppostophy]" id="hf_facility_lname" tabindex="4" value="<?php echo $this->formdata['hf_facility_lname']?>" size="15" maxlength="150"/></td>
  </tr>
</table>
       </td>
     </tr>
     <tr>
      <td class="label-no">Specialty</td>
      <td class="label-no">:</td>
      <td colspan="2"><select name="hf_speciality" onchange="checkoption(this.value)" style="width:200px;">
    <?php
	foreach($this->speciality as $sp)
	{
		echo '<option value="'.$sp['sp_name'].'">'.$sp['sp_name'].'</option>';
	}
	?>
      <option value="Other">other</option>
    </select><?php $this->DisplayHelp('UserRegistrtion','Speciality');?></td>
      <td>&nbsp;</td>
      <td colspan="2" id="other" style="visibility:hidden;"><input name="hf_speciality_other" type="text" id="hf_speciality_other" maxlength="150" value="<?php echo $this->formdata['hf_speciality']?>" tabindex="5"  /></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="label-no">Email ID</td>
      <td class="label-no">:</td>
      <td colspan="7"><input name="hf_email" type="text" class="validate[required],custom[email],ajax[ajaxUserEmail]" id="hf_email" tabindex="6" value="<?php echo $this->formdata['hf_email']?>" size="45" maxlength="150"/></td>
    </tr>
    <tr>
      <td class="label-no">Password</td>
      <td class="label-no">:</td>
      <td colspan="7" class="label-no"><table border="0" align="left" cellpadding="0" cellspacing="0">
  <tr>
    <td colspan="2"><input name="dashboard_password" type="password" class="validate[required],custom[password]" id="dashboard_password" tabindex="7" size="15" maxlength="15"  autocomplete="off" onkeyup="chkPass(this.value);" /></td>
    <td>&nbsp;</td>
    <td colspan="2" align="right" class="label-no">Confirm Password</td>
    <td class="label-no">:</td>
    <td><input name="dashboard_password_confirm" type="password" class="validate[required],equals[dashboard_password]" id="dashboard_password_confirm" tabindex="8" size="15" maxlength="150"/></td>
    <td>&nbsp;</td>
  </tr>
</table></td>
    </tr>
    <tr>
      <td class="label-no">Address</td>
      <td class="label-no">:</td>
      <td colspan="4"><textarea name="hf_address" id="hf_address" rows="5"  tabindex="9" class="validate[required]" style="width:219px;border-color:#FFF;border:1px;"><?php echo $this->formdata['hf_address']?></textarea></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="label-no">Country</td>
      <td class="label-no">:</td>
      <td colspan="5"><select name="hf_country" id="hf_country"  class="validate[required]" tabindex="10"  style="width:315px;" onchange="checkstate(this.value)" >
          <?php 
		  $selcountry=$this->formdata['hf_country'];
		  if($selcountry=="")
		  	$selcountry="USA";
		  foreach($this->country as $country)
		  {
		  	
		  	
		  	if($selcountry==$country['Code'])
		  	{
		  		$selval = " selected";
		  	}
		  	else
		  	{
		  		$selval ="";
		  	}
		  	echo "<option value='".$country['Code']."' ".$selval.">".$country['Name']."</option>";
		   
		  }
		  ?>
      </select></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="label-no">State </td>
      <td class="label-no">:</td>
      <td colspan="2"><select name="hf_state" tabindex="11">
       <?php
	   foreach($this->state as $st)
	   {
		   echo '<option value="'.$st['State_name'].'">'.$st['State_name'].'</option>';
	   }
	   ?>
     </select></td>
      <td>&nbsp;</td>
      <td colspan="2" id="otherstate" class="write-box" style="visibility:hidden;"><input name="hf_state_other" type="text" id="hf_state_other" maxlength="150" value="<?php echo $this->formdata['hf_state']?>" tabindex="12"/></td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="label-no">City</td>
      <td class="label-no">:</td>
      <td colspan="3"><input name="hf_city" type="text" id="hf_city" maxlength="150" class="validate[required]" value="<?php echo $this->formdata['hf_city']?>" tabindex="13"/></td>
      <td colspan="2" class="label-no">&nbsp;</td>
      <td class="label-no">&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="label-no">Postal / zip Code</td>
      <td class="label-no">:</td>
      <td><input name="hf_zip" type="text" id="hf_zip" maxlength="150" class="validate[required]" value="<?php echo $this->formdata['hf_zip']?>" tabindex="14"  style="width:115px;"/></td>
      <td colspan="3">&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td class="label-no">Phone Number</td>
      <td class="label-no">:</td>
      <td><input name="hf_phone" type="text" id="hf_phone" value="<?php echo $this->formdata['hf_phone']?>" size="10" maxlength="15" class="validate[required]" tabindex="15" style="width:115px;"/><?php $this->DisplayHelp('UserRegistrtion','PhoneNumber');?></td>
      <td colspan="3">&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    <tr>
      <td align="right" ><input type="checkbox" name="terms" id="terms"  class="validate[required]"/>
      <label for="terms"></label></td>
      <td class="normal-text" >:</td>
      <td colspan="7" class="normal-text" >I Agree <a href="<?php echo $this->baseUrl();?>/General/terms-of-Use/?keepThis=true&TB_iframe=true&height=400&width=700" class="thickbox" title="Terms of Use">Terms &amp; Conditions</a></td>
    </tr>
    <tr>
      <td >&nbsp;</td>
      <td >&nbsp;</td>
      <td ><input type="submit" name="Submit" id="Submit" value="Register Details" class="user-submit" tabindex="16" /></td>
      <td >&nbsp;</td>
      <td >&nbsp;</td>
      <td >&nbsp;</td>
      <td >&nbsp;</td>
      <td >&nbsp;</td>
      <td >&nbsp;</td>
    </tr>
  </table>
</form>
