<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/accordion.js';?>"></script>

<?php 
//echo "<pre>";
//print_r($this->faqlist);
?>
<style type="text/css">
		/* A few IE bug fixes */
		* { margin: 0; padding: 0; }
		* html ul ul li a { height: 100%; }
		* html ul li a { height: 100%; }
		* html ul ul li { margin-bottom: -1px; }
		
		#theMenu { width: 650px; height: 300px; margin: 5px 0; }
		
		/* Some list and link styling */
		ul li {
	width: 625px;
	font-family: Tahoma, Geneva, sans-serif;
	font-size: 11px;
	font-weight: normal;
}
		ul ul li { padding: 0;  margin-bottom: 0; }
		ul ul li a { display:block; color: #000; padding: 3px 6px; font-size: small; }
		ul ul li a:hover { display:block; color: #369; background-color: #eee; padding: 3px 8px; font-size: small; }
		li { list-style-type: none; }
		h2 { margin-top: 1.5em; }
		
		/* Header links styling */
		h3.head a {
	color: #333;
	display:block;
	border-top: 1px solid #36a;
	border-right: 1px solid #36a;
	background: #ddd url(down.gif) no-repeat;
	background-position: 98% 50%;
	padding: 3px 6px;
	font-family: Tahoma, Geneva, sans-serif;
	font-size: 11px;
	font-weight: bold;
		}
		h3.head a:hover { 
		color: #000;
		background: #ccc url(down.gif) no-repeat; 
		background-position: 98% 50%;
		}
		h3.selected a { 
		background: #69c url(up.gif) no-repeat; 
		background-position:98% 50%;
		color: #fff;
		padding: 3px 6px;
		}
		h3.selected a:hover { 
		background: #69c url(up.gif) no-repeat; 
		background-position:98% 50%;
		color: #36a;
		}
	</style>
<script type="text/javascript">
	$(document).ready(function(){	
	// applying the settings
	jQuery('#theMenu').Accordion({
		active: 'h3.selected',
		header: 'h3.head',
		alwaysOpen: false,
		animated: true,
		showSpeed: 300,
		hideSpeed: 300
	});
});	
</script>
	<ul id="theMenu">
	<?php 
	foreach($this->faqlist as $FAQ)
	{
    ?>
    <li>
				<h3 class="head"><a href="javascript:;"><?php echo $FAQ['question'];?></a></h3>
				<ul>
					<li><?php echo $FAQ['answer'];?></li>
				</ul>
			</li>
    <?php 
	}
	?>
	</ul>
