 <script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#adminlogin").validationEngine();
            });
  </script>
<div class="admin-login">
<div class="admin-title shadow">Enter Login Information</div>
<form id="adminlogin" method="post" action="">
<table width="40%" border="0" cellpadding="5" cellspacing="10" class="admin-login-box">
  <tr>
    <td height="80">&nbsp;</td>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td>User Id </td>
    <td>:</td>
    <td><input name="uid" type="text" id="uid" class="validate[required],custom[onlyLetterNumber]" tabindex="1" /></td>
  </tr>
  <tr>
    <td>Password</td>
    <td>:</td>
    <td><input name="pwd" type="password" id="pwd" class="validate[required],custom[onlyLetterNumber]" tabindex="2" /></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><input name="login" type="submit" id="login" value="Login" /></td>
  </tr>
</table>
</form>
</div>
<div class="confidality">
<span>WARNING!</span> ACCESS AND USE OF THIS COMPUTER SYSTEM BY ANYONE WITHOUT THE PERMISSION OF ZH HEALTHCARE IS STRICTLY PROHIBITED BY STATE AND FEDERAL LAWS AND MAY SUBJECT AN UNAUTHORIZED USER, INCLUDING EMPLOYEES NOT HAVING AUTHORIZATION, TO CRIMINAL AND CIVIL PENALTIES AS WELL AS COMPANY-INITIATED DISCIPLINARY ACTION.
</div>
