<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<div id="right_panel">
  <table width="100%" border="0" cellspacing="2" cellpadding="2">
    <tr>
      <td width="4%">&nbsp;</td>
      <td width="96%"><a href="<?php echo $this->baseUrl();?>/Admin/Acl/rolelist">Manage Roles</a></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td><a href="<?php echo $this->baseUrl();?>/Admin/Acl/resourcelist">Manage Resources</a></td>
    </tr>
     <!-- tr>
      <td>&nbsp;</td>
      <td><a href="<?php echo $this->baseUrl();?>/Admin/Acl/privilege">Manage Privileges</a></td>
    </tr-->
    <tr>
      <td>&nbsp;</td>
      <td><a href="<?php echo $this->baseUrl();?>/Admin/Acl/group-permission">Group (role) Permission Setting</a></td>
    </tr>
      <tr>
      <td>&nbsp;</td>
      <td><a href="<?php echo $this->baseUrl();?>/Admin/Acl/link-resource-to-role">User Permissions</a></td>
    </tr>
  </table>

</div>