<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<link href="../../../../../../public/css/admin.css" rel="stylesheet" type="text/css" />

<div id="right_panel">
<form action="" method="post">
<table width="100%" border="0" cellspacing="2" cellpadding="4">
  <tr>
    <td colspan="3" class="list-table-header shadow">Add New Privilages</td>
    </tr>
  <tr>
    <td class="label b shadowlight">Privilege Name</td>
    <td class="label b shadowlight">:</td>
    <td nowrap="nowrap" class="label shadowlight">&nbsp;<input type="text" name="privilege" id="privilege" /></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td nowrap="nowrap"><input type="submit" name="button" id="button" value="Add" /></td>
  </tr>
</table>

</form>
</div>