<?php
	if($this->sec=="group")
	{
		?>
        <select name="roleid" onchange="resourcelistgroup(<?php echo $this->cusid;?>)">
          <option value="0">Select One Role (Group)</option>
          <?php
		  foreach($this->rolelist as $RL)
		  {
			echo '<option value="'.$RL['id'].'">'.$RL['name'].'</option>';
		  }
		  ?>
        </select>
        <?php
	}
	else
	{
		?>
<table width="95%">
<?php 
foreach($this->rolelist as $RL)
{
?>
	<tr>
	<td><input type="radio" id="<?php echo $RL['id'];?>" name="role" onclick=resourcelist('<?php echo $RL['id']?>','<?php echo $RL['customer_id']?>',this.checked)></td>
	<td class="label b shadowlight" width="100%"><?php echo $this->escape($RL['name']);?></td>
	</tr>
<?php 
}
?>
</table>
<?php
	}
	?>