<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<link href="../../../../../../public/css/admin.css" rel="stylesheet" type="text/css" />

<div id="right_panel">
<form action="" method="post">
<table width="100%" border="0" cellspacing="2" cellpadding="4">
  <tr>
    <td colspan="3" class="list-table-header shadow">Add New Role</td>
    </tr>
  <tr>
    <td class="label b shadowlight">Select&nbsp;/ Add Reseller</td>
    <td class="label b shadowlight">:</td>
    <td nowrap="nowrap" class="label shadowlight"><select name="ex_cusid" id="ex_cusid">
      <option value="0" selected="selected">Select Reseller</option>
        <?php 
      foreach($this->ResellerList as $RL)
      {
          echo '<option value="'.$RL['id'].'">'.$RL['Name'].'</option>';
      }
      ?>
    </select>
      &nbsp;Or Add new Reseller 
      <input type="text" name="new_reseller" id="new_reseller" /></td>
  </tr>
  <tr>
    <td class="label b shadowlight">Select / Add Role Name</td>
    <td class="label b shadowlight">:</td>
    <td nowrap="nowrap" class="label shadowlight"><select name="ex_role" id="ex_role">
      <option value="0" selected="selected">Select Role</option>
     <?php 
      foreach($this->RoleList as $RL)
      {
          echo '<option value="'.$RL['name'].'">'.$RL['name'].'</option>';
      }
      ?>
    </select> 
      Or Add New Role : 
      <input type="text" name="new_role" id="new_role" /></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td nowrap="nowrap"><input type="submit" name="button" id="button" value="Add" /></td>
  </tr>
</table>

</form>
</div>