<br /><br /><h1><center> <b>Welcome member </b></center></h1>
<?php 
//$this->placeholder('sidebar')->append('<p><b>List of Members :</b> ' ) ;
//$this->placeholder('sidebar')->append('John User2: ' ) ;
//$this->placeholder('sidebar')->append('Christos User3:' ) ;
//$this->placeholder('sidebar')->append('Doe User4: ' ) ;
//$this->placeholder('sidebar')->append('Foo User5: ' ) ;
//$this->placeholder('sidebar')->append('XYZ User6: ' ) ;
//$this->placeholder('sidebar')->append('WFSA User7: ' ) ;
//$this->placeholder('sidebar')->append('Sinatra User8: ' ) ;
//$this->placeholder('sidebar')->append('ZZZsys User9: ' ) ;	
  ?>
 