	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/jquery/db/themes/base/jquery.ui.all.css">
	<script src="<?php echo $this->baseUrl();?>/jquery/db/external/jquery.bgiframe-2.1.2.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.core.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.widget.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.mouse.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.button.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.draggable.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.position.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.dialog.js"></script>
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/jquery/db/demo/demos.css">
	<script>
	$(function() {
		$("#dialog-confirm").addClass("hidevisible");  
		});
	
	
	function del(delid)
	{
		$(function() {
		$( "#dialog-confirm" ).addClass("shovisible");
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
			$( "#dialog-confirm" ).dialog({
				resizable: false,
				height:180,
				modal: true,
				buttons: {
					"Delete all items": function() {
						$( this ).dialog( "close" );
						window.location.href="<?php echo $this->baseUrl();?>/Admin/PageHelp/delete/id/"+delid+"";
					},
					Cancel: function() {
						$( this ).dialog( "close" );
					}
				}
			});
		});
	}
	
	</script>
<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
 <link href="../../../../../../public/css/admin.css" rel="stylesheet" type="text/css" />
<div id="dialog-confirm" title="Delete Record?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>The item will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>
<table width="82%" border="0" align="center">
 <tr>
    <td colspan="5"  align="right" valign="top" class="list-table-details"><table width="100%" border="0" cellspacing="0" cellpadding="0">
      <tr>
        <td width="39%" align="right" class="add">Search : </td>
        <td width="38%" align="right">
        <form action="" method="post">
        <table border="0" cellspacing="2" cellpadding="2">
          <tr>
            <td nowrap="nowrap" class="sub-head2">&nbsp;</td>
            <td><span class="sub-head2">Module</span><br />
                    
              <input type="text" name="module" id="module" value="<?php if(sizeof($this->formdata)>0) echo $this->formdata['module'];?>" /></td>
            <td nowrap="nowrap" class="sub-head2">&nbsp;</td>
            <td><span class="sub-head2">Section</span><br />              
              <input type="text" name="sec" id="sec"  value="<?php if(sizeof($this->formdata)>0) echo $this->formdata['sec'];?>" /></td>
             <td><input type="image" src="<?php echo $this->baseUrl();?>/images/Search.png" width="32" height="32" alt="Search" title="Search" /></td>
          </tr>
        </table>
        </form></td>
        <td width="23%" align="right"><table border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td><img src="<?php echo $this->baseUrl();?>/images/add.png" alt='Add' title='Add' /></td>
            <td nowrap="nowrap"><?php echo '<a href="'.$this->url(array('module'=>'Admin','controller'=>'PageHelp','action'=>'add'),0,true).'" class="add">';?> Add New Help <?php echo "</a>";?></td>
          </tr>
        </table></td>
      </tr>
    </table></td>
  </tr>
  <tr>
    <td colspan="5"  align="center" valign="top" class="list-table-details" id="alert">
    <span id="con_mess">
   <?php 
   echo $this->pss;
    ?>
    </span>
    </td>
    </tr>
  <tr>
    <td class="list-table-header">Module</td>
    <td class="list-table-header" align=center>Section</td>
	<td class="list-table-header" align=center>Title</td>
	<td align=center nowrap="nowrap" class="list-table-header">To Do</td>
  </tr>
 
  
<?php 
if(sizeof($this->helplist)==0)
{
	echo "<tr><td colspan='5'>no record found</td></tr>";
}
else
{
$i=1;
		foreach($this->helplist as $record)
	{

		echo($i%2==0)? "<tr class='list-tr-bg2'>": "<tr class='list-tr-bg'>";
		echo "<td class='list-table-details'>".$record['module']."</td>";
		echo "<td align=center class='list-table-details'>".$record['section']."</td>";
		echo "<td align=left class='list-table-details'>".$record['title']."</td>";
		echo "<td class='list-table-details' align='center'>";
		
		echo '<a href="'.$this->url(array('module'=>'Admin','controller'=>'Videogallery','action'=>'Index', 'id'=>$this->Ecode($record['page_help_id'])),0,true).'">';
		echo "<img src='".$this->baseUrl()."/images/youtube.png' alt='Video Gallery (link youtube video)' title='Video Gallery (link youtube video)'  style='cursor:pointer;' />";
		echo '</a>&nbsp;';
		
		echo '<a href="'.$this->url(array('module'=>'Admin','controller'=>'Imagegallery','action'=>'index', 'id'=>$this->Ecode($record['page_help_id'])),0,true).'">';
		echo "<img src='".$this->baseUrl()."/images/imagegallery.png' alt='Imagegallery' title='Imagegallery'  style='cursor:pointer;' />";
		echo '</a>&nbsp;';
		
		echo '<a href="'.$this->url(array('module'=>'Admin','controller'=>'PageHelp','action'=>'edit', 'id'=>$this->Ecode($record['page_help_id'])),0,true).'">';
		echo "<img src='".$this->baseUrl()."/images/edit.png' alt='Edit' title='Edit'  style='cursor:pointer;' />";
		echo '</a>&nbsp;';
		
		echo "<img src='".$this->baseUrl()."/images/delete.gif' alt='Delete' title='Delete' onClick='del(".$record['page_help_id'].")'   style='cursor:pointer;'/>";
		echo "</td>";
		echo "</tr>";
		$i++;
	}
}
?>
 <tr>
    <td colspan="4" align="right" nowrap="nowrap">
		<table>
	    	<tr>
    			<td><?php echo $this->paginationControl($this->helplist, 'Sliding', 'pagination.phtml'); ?></td>
        		<td><?php echo $this->paginationControl($this->helplist, 'Sliding', 'pagination_dropdown.phtml'); ?></td>
  			</tr>
  		</table>
  </td>
  </tr>
</table>

