<?php 
//echo $this->index["cms_details"];
?>
<link href="../../../../public/css/site.css" rel="stylesheet" type="text/css" />
<div id="welcome">
<div class="title">
<?php echo  $this->index['cms_title'];?>
</div>
<div class="dtd">
<?php echo $this->index['cms_details'];?>
</div>
</div>
<div class="plan-title shadow">Please click on any one of the available plans below to start your signup process</div>
<div class="plan-outer">
<?php 
$currency = new Zend_Currency('en_US');
foreach($this->plans as $plans)
{
    $path = $imgwithpath = str_replace("application", "public", APPLICATION_PATH).'\\uploads\\plans\\'.$plans['Imagename'];
 	if(file_exists($path))
 	{
 		$img = $this->baseUrl()."/uploads/plans/".$plans['Imagename'];
 	}
 	else
 	{
 	    $img = $this->baseUrl()."/uploads/plans/default.jpg";
 	}
    ?>

<div class="plan shadowlight">
<div class="imgbox"><a href="PlanList/listplan/id/<?php echo $this->Ecode($plans['hp_id']);?>"><img src="<?php echo $img;?>" width="190" height="215" /></a></div>
<div class="plan-name"><a href="PlanList/listplan/id/<?php echo $this->Ecode($plans['hp_id']);?>"><?php echo stripslashes($plans['hp_name']);?></a>
</div>
<div class="price">
<span class="strike">List Price : <?php echo $currency->toCurrency($plans['listprice']);?></span>
<br />Plan Price : <?php echo $currency->toCurrency($plans['bundle_cost']);?><br /> (Per  Provider/Month)
</div>
</div>
<?php 
}
?>

</div><div class="compareplan"><a href="PlanList/compareplans" class="button">Compare Plans</a></div>
<div class="clear">&nbsp;</div>