<?php $this->placeholder('sidebar')->captureStart() ?>
<script type="text/javascript">document.documentElement.className += " js";</script>

<script language="javascript">
//-------------------------------------------------------------------
// This program is free software; you can redistribute it and/or
// modify it under the terms of the GNU General Public License
// as published by the Free Software Foundation; either version 2
// of the License, or (at your option) any later version.
//-------------------------------------------------------------------
function SHA1 (msg) {
	function rotate_left(n,s) {
		var t4 = ( n<<s ) | (n>>>(32-s));
		return t4;
	};
	function lsb_hex(val) {
		var str="";
		var i;
		var vh;
		var vl;
		for( i=0; i<=6; i+=2 ) {
			vh = (val>>>(i*4+4))&0x0f;
			vl = (val>>>(i*4))&0x0f;
			str += vh.toString(16) + vl.toString(16);
		}
		return str;
	};
	function cvt_hex(val) {
		var str="";
		var i;
		var v;
		for( i=7; i>=0; i-- ) {
			v = (val>>>(i*4))&0x0f;
			str += v.toString(16);
		}
		return str;
	};
	function Utf8Encode(string) {
		string = string.replace(/\r\n/g,"\n");
		var utftext = "";
		for (var n = 0; n < string.length; n++) {
			var c = string.charCodeAt(n);
			if (c < 128) {
				utftext += String.fromCharCode(c);
			}
			else if((c > 127) && (c < 2048)) {
				utftext += String.fromCharCode((c >> 6) | 192);
				utftext += String.fromCharCode((c & 63) | 128);
			}
			else {
				utftext += String.fromCharCode((c >> 12) | 224);
				utftext += String.fromCharCode(((c >> 6) & 63) | 128);
				utftext += String.fromCharCode((c & 63) | 128);
			}
		}
		return utftext;
	};
	var blockstart;
	var i, j;
	var W = new Array(80);
	var H0 = 0x67452301;
	var H1 = 0xEFCDAB89;
	var H2 = 0x98BADCFE;
	var H3 = 0x10325476;
	var H4 = 0xC3D2E1F0;
	var A, B, C, D, E;
	var temp;
 
	msg = Utf8Encode(msg);
	var msg_len = msg.length;
	var word_array = new Array();
	for( i=0; i<msg_len-3; i+=4 ) {
		j = msg.charCodeAt(i)<<24 | msg.charCodeAt(i+1)<<16 |
		msg.charCodeAt(i+2)<<8 | msg.charCodeAt(i+3);
		word_array.push( j );
	}
	switch( msg_len % 4 ) {
		case 0:
			i = 0x080000000;
		break;
		case 1:
			i = msg.charCodeAt(msg_len-1)<<24 | 0x0800000;
		break;
 
		case 2:
			i = msg.charCodeAt(msg_len-2)<<24 | msg.charCodeAt(msg_len-1)<<16 | 0x08000;
		break;
 
		case 3:
			i = msg.charCodeAt(msg_len-3)<<24 | msg.charCodeAt(msg_len-2)<<16 | msg.charCodeAt(msg_len-1)<<8	| 0x80;
		break;
	}
 
	word_array.push( i );
	while( (word_array.length % 16) != 14 ) word_array.push( 0 );
	word_array.push( msg_len>>>29 );
	word_array.push( (msg_len<<3)&0x0ffffffff );
	for ( blockstart=0; blockstart<word_array.length; blockstart+=16 ) {
 
		for( i=0; i<16; i++ ) W[i] = word_array[blockstart+i];
		for( i=16; i<=79; i++ ) W[i] = rotate_left(W[i-3] ^ W[i-8] ^ W[i-14] ^ W[i-16], 1);
		A = H0;
		B = H1;
		C = H2;
		D = H3;
		E = H4;
		for( i= 0; i<=19; i++ ) {
			temp = (rotate_left(A,5) + ((B&C) | (~B&D)) + E + W[i] + 0x5A827999) & 0x0ffffffff;
			E = D;
			D = C;
			C = rotate_left(B,30);
			B = A;
			A = temp;
		}
		for( i=20; i<=39; i++ ) {
			temp = (rotate_left(A,5) + (B ^ C ^ D) + E + W[i] + 0x6ED9EBA1) & 0x0ffffffff;
			E = D;
			D = C;
			C = rotate_left(B,30);
			B = A;
			A = temp;
		}
		for( i=40; i<=59; i++ ) {
			temp = (rotate_left(A,5) + ((B&C) | (B&D) | (C&D)) + E + W[i] + 0x8F1BBCDC) & 0x0ffffffff;
			E = D;
			D = C;
			C = rotate_left(B,30);
			B = A;
			A = temp;
		}
		for( i=60; i<=79; i++ ) {
			temp = (rotate_left(A,5) + (B ^ C ^ D) + E + W[i] + 0xCA62C1D6) & 0x0ffffffff;
			E = D;
			D = C;
			C = rotate_left(B,30);
			B = A;
			A = temp;
		}
 		H0 = (H0 + A) & 0x0ffffffff;
		H1 = (H1 + B) & 0x0ffffffff;
		H2 = (H2 + C) & 0x0ffffffff;
		H3 = (H3 + D) & 0x0ffffffff;
		H4 = (H4 + E) & 0x0ffffffff;
 	}
 	var temp = cvt_hex(H0) + cvt_hex(H1) + cvt_hex(H2) + cvt_hex(H3) + cvt_hex(H4);
 	return temp.toLowerCase();
 }
</script>


 <script type="text/javascript">

    $(document).ready(function(){
        $(".tabs").accessibleTabs({
            tabhead:'h2',
            fx:"fadeIn"
        });
	
	$("#facility").blur(function(){
	    $.ajax({
	    type: "POST",
	    url: "<?php echo $this->baseUrl();?>/validate/validateUser.php",
	    dataType: "html",
	    data: {
	       facility: $("#facility").val(),
	       Source: "getServer",
	    },
	    async: false,
	    success: function(data){
	       if(data!=""){
		  $("#formaction").val(data);
	       }
	       else{
		  $("#formaction").val("");
		  alert("Invalid Facility");
	       }
	    }
	    });
	});
      	 
    });
      function formsubmit(){
	 if($("#formaction").val()){
	    document.forms[0].authNewPass.value=SHA1(document.forms[0].clearPass.value);
	    document.forms[0].authPass.value=SHA1(document.forms[0].clearPass.value);
	    document.forms[0].clearPass.value="";
	 //alert($("#formaction").val()+"/hostedemr/interface/main/main_screen.php?auth=login&site="+$("#facility").val());
	 $("#emrlogin").attr("action",$("#formaction").val()+"/hostedemr/interface/main/main_screen.php?auth=login&site="+$("#facility").val());
	 return true;
	// $.post(
	//    $("#formaction").val()+"/hostedemr/interface/main/main_screen.php?auth=login&site="+$("#facility").val(),
	//    $("#emrlogin").serialize(),
	//    function(thedata){
	//       if(thedata=="success"){
	//	  alert("OK");
	//       }
	//       else{
	//	  alert("FAILED");
	//       }
	//    }
	// );
	 }
	 else{
	    alert("Invalid Facility");
	 }
      }
    </script>  
<link href="../../../../public/css/site.css" rel="stylesheet" type="text/css" />
 <?
	if($this->loginerror=="not")
	{
		echo "<span class='normal-text'>Please check your user id and password.</span>";
	}
  ?>
   <div class="tabs">
        <h2>ZH OpenEMR</h2>
        <h2>My Account</h2>
        <div class="tabbody">
      <form id="emrlogin" action="" method="post">
      <table width="81%" border="0" align="center" cellpadding="2" cellspacing="4">
	 <tr>
	    <td>
	 <?php if ($_GET['error'] == 1 && $_GET['site']==''): ?>
	<tr><td colspan="3" class="form-label-main" style='color:red'>
	Invalid User Name or Password
	</td></tr>
	<?php endif; ?>
	 <?php if ($_GET['error'] == 2 && $_GET['site']==''): ?>
	<tr><td colspan="3" class="form-label-main" style='color:red'>
	Invalid Facility
	</td></tr>
	<?php endif; ?>
		<?php if ($_GET['error'] == 3 && $_GET['site']==''): ?>
	<tr><td colspan="3" class="form-label-main" style='color:red'align="justify">
	Password security has recently been upgraded.Please login again.
	</td></tr>
	<?php endif; ?>
        <tr>
          <td class="form-label-main">Facility</td>
          <td>:</td>
          <td><input type="text" name="facility" id="facility" /></td>
        </tr>
        <tr>
          <td class="form-label-main">User Id</td>
          <td>:</td>
          <td><input type="text" name="authUser" id="authUser" /></td>
        </tr>
        <tr>
          <td class="form-label-main">Password</td>
          <td>:</td>
          <td><input type="password" name="clearPass" id="clearPass" /></td>
        </tr>
	<tr>
          <td colspan="3" align="right"><input name="submit" onclick="return formsubmit()" type="submit" class="login" value="Login" /></td>
        </tr>
      </table>
	 <input type="hidden" name="authPass" id="authPass">
	 <input type="hidden" name="authNewPass" id="authNewPass">
	 <input type="hidden" name="formaction" id="formaction">
	 <input type='hidden' name='authProvider' value='Default' />
      </form>
        </div>
        <div class="tabbody">
             <form action="<?php echo $this->baseUrl();?>/Usercheck" method="post">
	  <table width="81%" border="0" align="center" cellpadding="2" cellspacing="4">
        <tr>
          <td class="form-label-main">Email ID</td>
          <td>:</td>
          <td><input type="text" name="uid" id="uid" /></td>
        </tr>
        <tr>
          <td class="form-label-main">Password</td>
          <td>:</td>
          <td><input type="password" name="pwd" id="pwd" /></td>
        </tr>
        <tr>
          <td colspan="2" align="right" nowrap="nowrap" class="normal-text">
          <a href="<?php echo $this->baseUrl();?>/Forgotpassword/?keepThis=true&TB_iframe=true&height=300&width=500" class="thickbox" title="Forgot Password">
          Forgot Password?
          </a>
          </td>
          <td align="right" ><input name="Submit2" type="submit" class="login" value="Submit" /></td>
        </tr>
      </table>
      </form>
<!--	  <a href="<?php echo $this->url(array('controller' => 'PlanList','action' => 'index')); ?>" class="td-plan-features">New Register</a>
-->        </div>

        
       
    </div>
<?php $this->placeholder('sidebar')->captureEnd() ?>