<?php
include_once  "/ckeditor/ckeditor.php";
$CKEditor = new CKEditor();
// Path to the CKEditor directory.
$CKEditor->basePath = $this->baseUrl().'/ckeditor/';
// Replace a textarea element with an id (or name) of "textarea_id" on last of page.

echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#cmsadd").validationEngine();
            });
</script>
<div id="right_panel">
  <form id="cmsadd" name="cmsadd" method="post" action="">
  <input type="hidden" name="faqid" value="<?php echo $this->faqview['faqid']?>"?>
    <table width="100%" border="0" cellspacing="4" cellpadding="4">
      <tr>
        <td colspan="3" class="list-table-header shadow">Add F A Q</td>
      </tr>
      <tr>
        <td class="label line">FAQ Section</td>
        <td>:</td>
        <td class="label line"><label for="category"></label>
          <select name="category" id="category">
            <option value="0" <?php if($this->faqview['category']=="0"){echo 'selected="selected"';}?>>General</option>
            <option value="1" <?php if($this->faqview['category']=="1"){echo 'selected="selected"';}?>>User</option>
        </select></td>
      </tr>
      <tr>
        <td width="19%" class="label line">FAQ Question</td>
        <td width="1%">:</td>
        <td width="80%" class="label line">
        <input name="question" type="text" id="question" size="50" maxlength="250"  class="validate[required]" value="<?php echo $this->faqview['question'];?>"/></td>
      </tr>
      <tr>
        <td class="label line">FAQ Answer</td>
        <td>:</td>
        <td class="label line">
        <textarea name="answer" id="answer" cols="45" rows="5"  class="validate[required]"><?php echo $this->faqview['answer'];?></textarea></td>
      </tr>
      <tr>
        <td class="label line">Listing Order</td>
        <td>:</td>
        <td class="label line"><label for="listing_order"></label>
        <input type="text" name="listing_order" id="listing_order"  value="<?php echo $this->faqview['listing_order'];?>"/></td>
      </tr>
      <tr>
        <td class="label line">Status</td>
        <td>:</td>
        <td class="label line">
          <p>
            <label>
              <input name="status" type="radio" id="status_0" value="1" <?php if($this->faqview['status']=="1"){echo 'checked="checked"';}?> />
              Active</label>
          
            <label>
              <input type="radio" name="status" value="0" id="status_1"  <?php if($this->faqview['status']=="0"){echo 'checked="checked"';}?>/>
              Disable</label>
            <br />
        </p></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td><input type="submit" name="button" id="button" value="Update" class="shadow" /></td>
      </tr>
    </table>
  </form>
</div>
<?php 
$CKEditor->replace("answer");
?>
<div class="clear"></div>
