<?php
include_once  "/ckeditor/ckeditor.php";
$CKEditor = new CKEditor();
// Path to the CKEditor directory.
$CKEditor->basePath = $this->baseUrl().'/ckeditor/';
// Replace a textarea element with an id (or name) of "textarea_id" on last of page.


?>
<link href="<?php echo $this->baseUrl();?>/css/admin.css" rel="stylesheet" type="text/css" />

<form id="form1" name="form1" method="post" action="">
<input type="hidden" name="hf_id" value="<?php echo $this->hf_id;?>" />
<input type="hidden" name="email" value="<?php echo $this->userdetails['hf_email'];?>" />
  <table width="100%" border="0" cellspacing="2" cellpadding="2">
    <tr>
      <td width="17%" class="label">To</td>
      <td width="1%" class="normal">:</td>
      <td width="82%" class="sub-head2"><?php echo $this->userdetails['hf_facility_suffix'];?>&nbsp;<?php echo $this->userdetails['hf_facility_name'];?>&nbsp;<?php echo $this->userdetails['hf_facility_lname'];?></td>
    </tr>
    <tr>
      <td class="label">Subject</td>
      <td class="normal">:</td>
      <td><input name="email_title" type="text" id="email_title" size="50" /></td>
    </tr>
    <tr>
      <td class="label">Message</td>
      <td class="normal">:</td>
      <td><textarea name="cms_details" id="cms_details" cols="45" rows="5"  class="validate[required]"><?php echo $this->cmsview['cms_details'];?></textarea></td>
    </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td><input type="submit" name="button" id="button" value="Send Email" /></td>
    </tr>
  </table>
</form>
<?php 
$CKEditor->replace("cms_details");
?>