<?php
$sess = new Zend_Session_Namespace('user');
$hf_id=$sess->hf_id;
?>
 <script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#userregister").validationEngine();
            });
  </script>
  <link href="../../../../../../public/css/user.css" rel="stylesheet" type="text/css" />
  
<div class="table-head-bg normal-text white b shadow"  style="width:90%;margin-left:10px;height:20px;padding-left:5px;padding-top:4px;">
Update Profile
</div>


<div class="clear"></div>

<form id="userregister" method="post" action="">
<table width="28%" border="0" cellspacing="2" cellpadding="0" align="center" id="userregister">
	<tr>
		<td colspan="2" class="normal-text red b">
		<?php 
		if($this->st=="y")
			echo "Successfully updated the records";
		?>
		</td>
	</tr>
	<tr>
	  <td class="form-label-main">Suffix</td>
	  <td class="form-label-main">First Name
      <?php $this->DisplayHelp('UserRegistrtion','name');?></td>
    </tr>
	<tr>
		<td class="form-label-main"><span class="write-box" style="width:65px;">
		  <select name="hf_facility_suffix" tabindex="2">
		    <option value="Dr." <?php echo($this->formdata['hf_facility_suffix']=='Dr.')?'selected="selected"':'';?>>Dr.</option>
		    <option value="Mr." <?php echo($this->formdata['hf_facility_suffix']=='Mr.')?'selected="selected"':'';?>>Mr.</option>
		    <option value="Miss." <?php echo($this->formdata['hf_facility_suffix']=='Miss.')?'selected="selected"':'';?>>Miss.</option>
		    <option value="Mrs." <?php echo($this->formdata['hf_facility_suffix']=='Mrs.')?'selected="selected"':'';?>>Mrs.</option>
	    </select>
		</span></td>
		<td class="form-label-main"><input name="hf_facility_name" type="text" id="hf_facility_name" value="<?php echo $this->formdata['hf_facility_name']?>" size="40" maxlength="150" class="validate[required]" tabindex="2"/></td>
	</tr>
	<tr>
		<td class="form-label-main">Last Name </td>
		<td class="form-label-main">Speciality <?php $this->DisplayHelp('UserRegistrtion','Speciality');?>
		</td>
	</tr>
	<tr>
		<td><input name="hf_facility_lname" type="text" id="hf_facility_lname" value="<?php echo $this->formdata['hf_facility_lname']?>" size="40" maxlength="150" class="validate[required]" tabindex="2"/></td>
		<td><input name="hf_speciality" type="text" id="hf_speciality" value="<?php echo $this->formdata['hf_speciality']?>" size="40" maxlength="150" class="validate[required]" tabindex="3"/></td>
	</tr>
	<tr>
		<td class="form-label-main">&nbsp;</td>
		<td class="form-label-main">&nbsp;</td>
	</tr>
	
	<tr>
		<td class="form-label-main">Email Address
        </td>
		<td class="form-label-main">&nbsp;</td>
	</tr>
	<tr>
		<td class="normal-text"><?php echo $this->formdata['hf_email']?></td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="form-label-main">&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td class="form-label-main">Address<?php $this->DisplayHelp('UserRegistrtion','StreetAddress');?></td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td colspan="2"><input name="hf_address" value="<?php echo $this->formdata['hf_address']?>" type="text" id="hf_address" size="70" maxlength="250" class="validate[required]" tabindex="8"/>
			<br />
		<span class="form-label-sub">Street Address</span></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td><input name="hf_city" type="text" id="hf_city" value="<?php echo $this->formdata['hf_city']?>" size="40" maxlength="150" class="validate[required]" tabindex="9"/>
			<br />
		<span class="form-label-sub">City</span></td>
		<td><input name="hf_state" type="text" id="hf_state" value="<?php echo $this->formdata['hf_state']?>" size="40" maxlength="150" class="validate[required]" tabindex="10"/>
			<br />
		<span class="form-label-sub">State / Province / Region</span></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	<tr>
		<td><input name="hf_zip" type="text" id="hf_zip" value="<?php echo $this->formdata['hf_zip']?>" size="40" maxlength="150" class="validate[required]" tabindex="11"/>
			<br />
		<span class="form-label-sub">Postal / Zip Code</span></td>
		<td>
		<select name="hf_country" id="hf_country"  class="validate[required]" tabindex="12">
		  <?php 
		  foreach($this->country as $country)
		  {
		  	if($this->formdata['hf_country']==$country['Code'])
		  	{
		  		$selval = " selected";
		  	}
		  	else
		  	{
		  		$selval ="";
		  	}
		  	echo "<option value='".$country['Code']."' ".$selval.">".$country['Name']."</option>";
		   
		  }
		  ?>
		</select>
		  <br />
		<span class="form-label-sub">Country</span></td>
	</tr>
	<tr>
		<td class="form-label-main">&nbsp;</td>
		<td class="form-label-main">&nbsp;</td>
	</tr>
	<tr>
		<td class="form-label-main">Phone Number<?php $this->DisplayHelp('UserRegistrtion','PhoneNumber');?></td>
		<td class="form-label-main">Fax<?php $this->DisplayHelp('UserRegistrtion','Fax');?></td>
	</tr>
	<tr>
		<td><input name="hf_phone" type="text" id="hf_phone" value="<?php echo $this->formdata['hf_phone']?>" size="10" maxlength="15" class="validate[required]" tabindex="13"/></td>
		<td><input name="hf_fax" type="text" id="hf_fax" value="<?php echo $this->formdata['hf_fax']?>" size="10" maxlength="15" class="validate[required]" tabindex="14"/></td>
	</tr>
	<tr>
		<td class="form-label-main">&nbsp;</td>
		<td class="form-label-main">&nbsp;</td>
	</tr>
	<tr>
		<td class="form-label-main">Tax ID<?php $this->DisplayHelp('UserRegistrtion','TaxID');?></td>
		<td class="form-label-main">NPI<?php $this->DisplayHelp('UserRegistrtion','NPI');?></td>
	</tr>
	<tr>
		<td><input name="hf_tax_id" type="text" id="hf_tax_id" value="<?php echo $this->formdata['hf_tax_id']?>" size="20" maxlength="150" class="validate[required]" tabindex="15"/></td>
		<td><input name="hf_npi" type="text" id="hf_npi" value="<?php echo $this->formdata['hf_npi']?>" size="25" maxlength="150" class="validate[required]" tabindex="16"/></td>
	</tr>
	<tr>
		<td>&nbsp;</td>
		<td>&nbsp;</td>
	</tr>
	 <?php if($this->checkacl('user','Profile','update',$hf_id)){?>
	<tr>
		<td>&nbsp;</td>
		<td><input type="submit" name="Submit" value="Update Details" class="user-submit" tabindex="17" /></td>
	</tr>
	<?php }?>

</table>
</form>
<p>&nbsp;</p>
