<br /><br />
<div class="normal-text" style="width:90%;margin-left:15px;">
	<p>Hi <?php echo $this->username;?>,	  </p>
	<p>Thanks for registering with ZH Healthcare. Your plan registration (<?php echo $this->planname;?>) completed successfully. </p>
	<p>We required 24 hours to setup the plan environment for you. Once the plan setup is completed, you will notify through your registered email address.	  </p>
	<p>Regards,</p>
	<p> ZH Healthcare Support Team </p>
	<p><a href="<?php echo $this->baseURL();?>/index">Back To Homepage</a></p>
</div>