<link href="../../../../public/css/user.css" rel="stylesheet" type="text/css" />
<script language="javascript" type="text/javascript">
function AddAdditionalProductIntoCart(productid,providerno,ival)
{
	if(ival) // for adding
	{
		$.ajax({
		  type: "GET",
		  url: "../../../../../Cart/add-additional-product",
		  data: { productid: ""+productid+"", providerno: ""+providerno+"", add:"add" }
		}).done(function( msg ) {
		  alert( msg );
		  location.reload();
		});
	}
	
}
function RemoveAdditionalProductFromCart(idcart)
{
	confirmdel = confirm("Are you sure to delete this product from cart?");
	if(confirmdel)
	{
		$.ajax({
		  type: "GET",
		  url: "../../../../../Cart/remove-additional-product",
		  data: { cartid: ""+idcart+"" }
		}).done(function( msg ) {
		  alert( msg );
		  location.reload();
		});	
	}
}
</script>
  <?php 
  if($this->cms)
  {
  		echo '<div class="cms">';
		if(!$this->cms['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cms['cms_details'];
	echo '</div>';
  }
?>
<table width="94%" border="0" align="center" cellpadding="2" cellspacing="2">
  <tr>
    <td align="left" class="cart-head">My Cart</td>
  </tr>
  <tr>
    <td align="left">
    <form method="post" action="<?php echo $this->baseURL();?>/payment/index/uid/<?php echo $this->uid;?>/pid/<?php echo $this->pid;?>">
    <table width="100%" border="0" cellspacing="2" cellpadding="2">
      <tr>
        <td width="2%" class="cart-title shadow">#</td>
        <td width="8%" class="cart-title shadow">Plan</td>
        <td width="37%" class="cart-title shadow">Plan Includes</td>
        <td width="9%" align="center" class="cart-title shadow">Providers</td>
        <td width="12%" align="right" nowrap="nowrap" class="cart-title shadow">Provider / Month</td>
        <td width="10%" align="right" nowrap="nowrap" class="cart-title shadow">One Time Fee</td>
        <td width="19%" align="right" class="cart-title shadow">Discount</td>
        <td width="3%" align="right">&nbsp;</td>
      </tr>
      <?php 
      $currency = new Zend_Currency('en_US');
      $gtotal=0;
	  $sino=1;
	  $gsetupfee=0;
	  $totaldiscount=0;
	  $totalunitprice=0;
	  $totalsetupfee=0;
	//  echo "<pre>";
	//  print_r($this->cart);
	//  echo "</pre>";
      foreach($this->cart as $cart)
      {
      ?>
      <tr>
        <td height="25" valign="top" class="normal-text shadowlight"><?php echo $sino;?>.</td>
        <td valign="top" class="normal-text shadowlight"><?php
		if(!$cart['plan_id']==0)
		 echo stripcslashes($cart['description']);?></td>
        <td valign="top" nowrap="nowrap" class="normal-text shadowlight">
        <?php
		if(!$cart['plan_id']==0)
		{
		echo "<ul class='cartul'>";
		foreach($this->prolist as $prolist)
		{
			
			echo '<li><a class="openmodalbox" href="javascript:void(0);"	rel="ajax: '.$this->baseUrl().'/user/Products/productfeature/id/'.base64_encode($prolist['idproducts']).'">'.$prolist['product_name'].'</a></li>';	
		}
		echo "</ul>";
		}
		else
		{
			echo stripcslashes($cart['description']);	
		}
		?>
        </td>
        <td align="center" valign="top" class="normal-text shadowlight"><?php echo $cart['qty'];?></td>
        <td align="right" valign="top" class="normal-text shadowlight">
        <?php 
        echo $currency->toCurrency($cart['unit_price']);
		$totalunitprice = $totalunitprice + $cart['unit_price'];
        ?>
        </td>
        <td align="right" valign="top" class="normal-text shadowlight">
         <?
		if($cart['setupfee']>0)
		{
			echo $currency->toCurrency($cart['setupfee']);
			$totalsetupfee = $totalsetupfee + $cart['setupfee'];
		}
		else
		{
			echo "$0.00";	
		}
		$totaldiscount = $totaldiscount + $cart['discount'];
          $currency->toCurrency(($cart['unit_price'])+$cart['setupfee']);
         $gtotal = $gtotal + (($cart['unit_price'])+$cart['setupfee']);
		?>
        </td>
        <td align="right" valign="top" class="normal-text shadowlight"><?php echo round($cart['discount']);?></td>
        <td align="right" valign="top" class="normal-text shadowlight">
        <?php
		if($cart['plan_id']==0)
		{
			echo '<img src="'.$this->baseUrl().'/images/delete.gif" width="16" height="16" alt="Delete" title="Delete" onclick="RemoveAdditionalProductFromCart('.$cart['idcart'].')"  style="cursor:pointer;"/>';	
		}
		?>
        </td>
        </tr>
       
     
    
      <?php 
	  $sino=$sino+1;
      }
	   if( $sino>1)
		  {
      ?>
       <tr>
          <td class="normal-text"></td>
          <td colspan="6" class="normal-text b line"></td>
          <td class="normal-text b" align="right"></td>
        </tr>
        <tr>
          <td class="normal-text"></td>
          <td colspan="2" class="normal-text b">Sub Total</td>
          <td class="normal-text b">&nbsp;</td>
          <td align="right" class="normal-text b"><?php echo $currency->toCurrency(round($totalunitprice));?></td>
          <td align="right" class="normal-text b"><?php echo $currency->toCurrency(round($totalsetupfee));?></td>
          <td class="normal-text b" align="right"><?php echo $currency->toCurrency(round($totaldiscount));?></td>
          <td width="3%" align="right" class="normal-text b">&nbsp;</td>
        </tr>
        <tr>
          <td class="normal-text"></td>
          <td colspan="6" class="normal-text b line"></td>
          <td class="normal-text b" align="right"></td>
        </tr>
        <tr>
        <td class="normal-text"></td>
        <td colspan="5" class="normal-text b">Gross Amount</td>
        <td class="normal-text b" align="right"><?php echo $currency->toCurrency(round(($gtotal+$gsetupfee)-$totaldiscount));?></td>
        <td class="normal-text b" align="right">&nbsp;</td>
        </tr>
        <tr>
          <td class="normal-text"></td>
          <td align="right" class="normal-text b"></td>
          <td align="right" class="normal-text b"></td>
          <td align="right" class="normal-text b">&nbsp;</td>
          <td align="right" nowrap="nowrap" class="normal-text b">
          <?php  if($this->planname =="")
 {?>
          <!--a href="<?php echo $this->baseURL();?>/user/Products" class="BrowseProducts shadow">Browse Products</a-->
          <?php }?>
          </td>
          <td align="right" nowrap="nowrap" class="normal-text b">&nbsp;</td>
          <td colspan="3" class="normal-text b" align="center">
        <?php
		if($gtotal==0)
		{
			?>
			<a href="<?php echo $this->baseURL();?>/Cart/Freeplan/pid/<?php echo $this->pid;?>" class="BrowseProducts shadow">Confirm Order</a>
			<?php 
		}
		else
		{
			?>
          <input type="submit" name="button" id="button" value="Confirm Order" class="submit shadow" />
        <?
		}
		?>
          </td>
        </tr>
          <? }
		  else
		  if($sino==1)
		  echo "<tr><td colspan='6' align=center>&nbsp;</td></tr><tr><td colspan='6' align=center class='normal-text red shadowlight'>Cart is Empty</td></tr>";
		  ?>
    </table>
    </form>
    </td>
  </tr>
  <tr>
  <td class="form-label-main">
   <?php 
  if($this->cmsadditional)
  {
  		echo '<div class="cms">';
		if(!$this->cmsadditional['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cmsadditional['cms_details'];
	echo '</div>';
  }
?>
  </td>
  </tr>
  <tr>
  <td>
 <!-- ADDITIONAL PRODUCT LISTING -->
 
 <table width="100%" border="0" cellspacing="2" cellpadding="2">
  <tr>
    <td width="3%" class="cart-title shadow">#</td>
    <td width="70%" class="cart-title shadow">Category</td>
    <td width="70%" nowrap="nowrap" class="cart-title shadow">Product Name</td>
    <td width="12%" align="right" class="cart-title shadow">Provider / Month</td>
    <td width="12%" align="right" nowrap="nowrap" class="cart-title shadow">One Time Fee</td>
    <!--td width="12%" align="left" nowrap="nowrap" class="cart-title shadow">Payment Term</td-->
    <td width="7%" class="cart-title shadow">Providers</td>
    <td width="7%" nowrap="nowrap" class="cart-title shadow">Total Cost</td>
    <td width="8%" nowrap="nowrap" class="cart-title shadow">Add To Cart</td>
  </tr>
  <?php 
 /*
  * Adding the products from cart_product_list function
  */
 echo $this->products;
  ?>
   <tr>
    <td height="25" class="normal-text"></td>
    <td class="normal-text">&nbsp;</td>
    <td height="25" class="normal-text">&nbsp;</td>
    <td height="25" class="normal-text">&nbsp;</td>
    <td height="25" class="normal-text">&nbsp;</td>
    <td height="25" class="normal-text">&nbsp;</td>
    <td height="25" class="normal-text">&nbsp;</td>
    <td height="25" class="normal-text">&nbsp;</td>
    <td height="25" nowrap="nowrap" class="normal-text">
   
    <!-- <a href="<?php echo $this->baseURL();?>/Cart/index/uID/<?php echo $this->Ecode($this->hf_id);?>/Pid/<?php echo $this->Ecode(0);?>" class="BrowseProducts shadow">View Cart</a> -->
    </td>
  </tr>
</table>
 <!-- END ADDITIONAL PRODUCT LISTING -->
  </td>
  </tr>
</table>
  
  
