<table width="80%" border="0" align="center" cellpadding="0" cellspacing="0">
  <tr>
    <td colspan="2" class="dashboard-welcome">
    <?php echo $this->welcome['cms_title'];?>&nbsp;
    <?php 
   echo $this->ufullname;
    ?> !!!
    </td>
  </tr>
  <tr>
    <td height="40" colspan="2" valign="top" class="line"><?php echo $this->welcome['cms_details'];?></td>
  </tr>
  <tr>
    <td width="57%" valign="top">
  
    </td>
    <td width="43%" rowspan="2" valign="top">
      <fieldset class="frameset-profile">
        <legend>Account Overview:</legend>
        <table width="100%" border="0" cellspacing="3" cellpadding="3">
  <tr>
    <td colspan="2" class="sec-heading">Last Payment :</td>
    </tr>
  <tr>
    <td colspan="2" class="sec-details">
    <?php 
	if(is_array($this->LastPayment_invoice))
 	{
		echo "Invoice No :";
 		echo "<a href='".$this->baseUrl()."/user/invoice/view/inid/".$this->Ecode($this->LastPayment_invoice['invoice_number'])."'. target=\"_blank\" class=\"popupwindow\" rel=\"height:488,width:635,toolbar:0,scrollbars:1,status:0,resizable:0,left:50,top:100\">"; 		
		echo $this->LastPayment_invoice['invoice_number']."</a><br>";
		echo "Date : ".$this->LastPayment_invoice['invoice_date'].".<br>";
		echo  "<div class=\"line\"></div>";
	}
	else
		echo $this->LastPayment_invoice;
	?>
	
      </td>
    </tr>
  <tr>
    <td colspan="2" class="sec-heading">Outstanding Payment :</td>
    </tr>
  <tr>
    <td colspan="2" class="sec-details">
    <?php 
    if(is_array($this->Outstanding_invoice))
    {
    	foreach($this->Outstanding_invoice as $outstanding)
    	{
	    	echo "Invoice No :";
 			echo "<a href='".$this->baseUrl()."/user/invoice/view/inid/".$this->Ecode($outstanding['invoice_number'])."'. target=\"_blank\" class=\"popupwindow\">";
	    	echo $outstanding['invoice_number'].",</a><br>";
	    	echo "Date : ".$this->Disdate($outstanding['invoice_date']).".";
	    	echo "</br><br/>";
    	}
    }
    else
    	echo $this->Outstanding_invoice;
		
		echo  "<div class=\"line\"></div>";
    ?>
    </td>
    </tr>
  <tr>
    <td width="33%" class="sec-heading">Plan Details:</td>
    <td width="67%" class="sec-details">
    <?php 
    echo "Plan Name : ".$this->PlanDetails['plan_name']."<br/>";
    echo "Plan Status : ".$this->PlanStatus($this->PlanDetails['plan_status'])."<br/>";
    if($this->PlanDetails['plan_status']==1)
    {
    	echo "Plan Activated Date : ".$this->Disdate($this->PlanDetails['plan_activated_date']);
    }
    if($this->PlanDetails['plan_status']==2)
    {
    	echo "Plan Disabled Date : ".$this->Disdate($this->PlanDetails['plan_disabled_date']);
    }
    if($this->PlanDetails['plan_status']==3)
    {
    	echo "Plan Expired Date : ".$this->Disdate($this->PlanDetails['plan_expired_date']);
    }
    ?>
    </td>
  </tr>
  <tr>
    <td colspan="2">&nbsp;</td>
    </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
  </tr>
        </table>

        </fieldset>
    </td>
  </tr>
  <tr>
    <td valign="top">
     
    </td>
  </tr>
  <tr>
    <td colspan="2"></td>
  </tr>
</table>
