<?php
if( $this->sec==0)
{
?>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#resetpass").validationEngine();
            });
</script>
<form id="resetpass" name="resetpass" method="post" action="">
<table width="98%" border="0" align="center" cellpadding="2" cellspacing="2">
  <tr>
    <td class="plan-title shadow">Reset Password</td>
  </tr>
  <tr>
    <td>&nbsp;</td>
  </tr>
  <tr>
    <td class="cms"><p>Hi <?php echo $this->userdata['hf_facility_suffix'];?> <?php echo $this->userdata['hf_facility_name'];?> <?php echo $this->userdata['hf_facility_lname'];?>,</p>
    <p>
     <?php 
  if($this->cms)
  {
  		echo '<div class="cms">';
		if(!$this->cms['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cms['cms_details'];
	echo '</div>';
  }
?>
    </p></td>
  </tr>
  <tr>
    <td>
    <table width="60%" border="0" align="center" cellpadding="2" cellspacing="2">
  <tr>
    <td class="label-no">Temporary Password</td>
    <td class="label-no">:</td>
    <td><label for="temppass"></label>
      <input type="password" name="temppass" id="temppass" class="validate[required]"/>
      <input type="hidden" name="hf_id" id="hf_id" value="<?php echo $this->hf_id;?>" />
      <span class="red">*</span></td>
  </tr>
  <tr>
    <td class="label-no">New Password</td>
    <td class="label-no">:</td>
    <td><label for="newpass"></label>
      <input type="password" name="newpass" id="newpass" class="validate[required],custom[password]" />
      <span class="red">*</span></td>
  </tr>
  <tr>
    <td class="label-no">Confirm New Password</td>
    <td class="label-no">:</td>
    <td><label for="confirmnewpass"></label>
      <input type="password" name="confirmnewpass" id="confirmnewpass" class="validate[required],equals[newpass]"/>
      <span class="red">*</span></td>
  </tr>
  <tr>
    <td>&nbsp;</td>
    <td>&nbsp;</td>
    <td><input type="submit" name="button" id="button" value="Reset Password" /></td>
  </tr>
</table>
    </td>
  </tr>
</table>
</form>
<?php
}
else
{

	
?>
<table width="98%" border="0" align="center" cellpadding="2" cellspacing="2">
  <tr>
    <td align="center" class="cms"><?php echo $this->message;?></td>
  </tr>
  <?
  if($this->noretry==0)
  {
	  ?>
   <tr>
    <td align="center"><a href="<?php echo $this->baseUrl();?>/Resetpassword/index/uid/<?php echo $this->hf_id;?>">Retry</a></td>
  </tr>
  <?
  }
  ?>
</table>

<?php	
}
?>