<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hosted EMR');
echo $this->doctype(); 

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
<link href="../../../public/css/admin.css" rel="stylesheet" type="text/css">
<head>
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<link href="<?php echo $this->baseUrl().'/css/admin.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/validationEngine.jquery.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid_jui.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/jquery-ui-1.8.4.custom.css';?>" rel="stylesheet" type="text/css" />
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.5.1.min.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine-en.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.dataTables.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/admin.js';?>"></script>


<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox-basic.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox.css" />
<script type="text/javascript">
/* <![CDATA[ */
	var pageType 	= "Modalbox";
	var webRoot 	= "<?php echo $this->baseUrl();?>";
	var isLocalhost = false;
/* ]]> */
</script>
<script src="<?php echo $this->baseUrl();?>/js/modelbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.modalbox-1.4.0-min.js"></script>


		
		
</head>
<body>
<div class="clear"></div>
<div id="main">
  <div id="content">
   <div id="details-popup">
    <?php echo $this->layout()->content; ?>

	</div>
 </div>
  <div class="clear"></div>
</div>
</body>
</html>

<script language="javascript">
$("#con_mess").delay(3000).fadeOut(800);
</script>

