<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hosted OpenEMR');
echo $this->doctype(); 

?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>
<link href="<?php echo $this->baseUrl().'/css/admin.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/validationEngine.jquery.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid_jui.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/jquery-ui-1.8.4.custom.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/thickbox.css';?>" rel="stylesheet" type="text/css" />



<script language="javascript" src="<?php echo $this->baseUrl();?>/jquery/db/jquery-1.7.1.js"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine-en.js';?>"></script>

<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.dataTables.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/thickbox.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.corner.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/admin.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.expander.js';?>"></script>

<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.core.js"></script>
<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.widget.js"></script>
<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.accordion.js"></script>



<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox-basic.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox.css" />
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/jquery/db/themes/base/jquery.ui.all.css">
<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/jquery/db/demo/demos.css">

<?php 
$leftmenu = new Zend_Session_Namespace('leftmenuid');
if($leftmenu->leftmenuid=='')
    $leftmenu->leftmenuid=10;
?>
<script type="text/javascript">
/* <![CDATA[ */
	var pageType 	= "Modalbox";
	var webRoot 	= "<?php echo $this->baseUrl();?>";
	var isLocalhost = false;
	
	$('#details').corner("round");
//	$('#leftmenu').corner("bite");
	//$('#con_mess').corner("Bevel");

	
	$(document).ready(function() {
		  $('div.features').expander({
		    slicePoint: 30,
		    widow: 2,
		    expandSpeed: 0,
			expandEffect: 'show',
		    userCollapseText: '[^]'
		  });
		});
	$(function() {
		$( "#accordion" ).accordion({
			collapsible: false,
			active:<?php echo $leftmenu->leftmenuid;?>
		});
	});
/* ]]> */
</script>
<script src="<?php echo $this->baseUrl();?>/js/modelbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.modalbox-1.4.0-min.js"></script>
<script type="text/javascript">
	//javascript: window.history.forward(1);
</script>

		
		
</head>
<body>
<table width="100%" cellpadding="0" cellspacing="0" border="0">
<tr>
<td colspan="2">
<div class="admin-header">
  <div class="header-logo"></div>
   
<div class="logout"> 

<a href="<?php echo $this->url(array('module'=>'Admin','controller'=>'Logout','action'=>'index'),0,true);?>"><img src="<?php echo $this->baseUrl();?>/images/logout.png" alt="Logout" border="0"></a> </div>
</div>
</td>
</tr>
<tr>
<td colspan="2">
<div id="main">
  <div id="content">
   <div id="details">
    <?php echo $this->layout()->content; ?>
	</div>
 </div>
</div>
</td>
</tr>
<tr>
<td>
<div id="footer">&copy; <?php echo date('Y');?> zhservices </div>

</td>
</tr>
<tr>
  <td></td>
</tr>
</Table>


</body>
</html>
<script type="text/JavaScript">
$("#con_mess").delay(3000).fadeOut(800);
</script> 


