<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hosted EMR');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>

<link href="<?php echo $this->baseUrl().'/css/site.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/validationEngine.jquery.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/tooltip.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/tabs.css';?>" rel="stylesheet" type="text/css" />

<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.5.1.min.js';?>"></script>
<!--script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.7.min.js';?>"></script-->
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine-en.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jtip.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.tabs.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/curvycorners.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.flash.js';?>"></script>

<script src="<?php echo $this->baseUrl()?>/js/cufon-yui.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/gnuolane.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/sony-sketch-ef.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/bodonitown.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/enigmatic.cufonfonts.js" type="text/javascript"></script>
<script type="text/javascript">
Cufon.replace('.plan-name', { fontFamily: 'Gnuolane Free', hover: true }); 
Cufon.replace('.plan-title', { fontFamily: 'Sony Sketch EF', hover: true }); 
Cufon.replace('.sub-title', { fontFamily: 'Sony Sketch EF', hover: true });
Cufon.replace('.cart-head', { fontFamily: 'Bodonitown', hover: true }); 
Cufon.replace('.cart-title', { fontFamily: 'Enigmatic Regular', hover: true });

</script>

<script type="text/javascript">
	//javascript: window.history.forward(1);
</script>
<script type="text/JavaScript">
  window.onload = function() {
    var settings = {
      tl: { radius: 5 },
      tr: { radius: 5 },
      bl: { radius: 5 },
      br: { radius: 5 },
      antiAlias: true
    }

    var divObj = document.getElementById("main");
    curvyCorners(settings, divObj);
    // or, equivalently:
    curvyCorners(settings, '.reg-steps');
    curvyCorners(settings, '.label-box');
    curvyCorners(settings, '.label-no');
    curvyCorners(settings, '.write-box');
  }


$(document).ready(function(){
    $('#bannerright').flash(
        { src: '<?php echo $this->baseUrl();?>/banner/banner.swf',
          width: 299,
          height: 337 },
        { version: 8 }
    );
});
</script> 

</head>
<body>
<?php require_once("./header.php");?>
<div id="main">
	<div id="content">
	<h1><?php echo $this->escape($this->title); ?></h1>
	<?php echo $this->layout()->content; ?>
	
	</div>
	<div id="login">
		<div id="leftnav">

<?php echo $this->placeholder('sidebar') ?>
<div id="bannerright">

</div>
</div>
 <div class="right-nav-bottom"></div>
	</div>
  
   
	<div class="clear"></div>
</div>
<div id="mainshadow">
</div>
<?php require_once("./footer.php");?>
</body>
</html>