<?php
error_reporting(0);
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hosted EMR');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>

<link href="<?php echo $this->baseUrl().'/css/site.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/validationEngine.jquery.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/tooltip.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/tabs.css';?>" rel="stylesheet" type="text/css" />

<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.5.1.min.js';?>"></script>
<!--script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.7.min.js';?>"></script-->
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine-en.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jtip.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.tabs.js';?>"></script>

<script src="<?php echo $this->baseUrl()?>/js/cufon-yui.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/gnuolane.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/sony-sketch-ef.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/bodonitown.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/enigmatic.cufonfonts.js" type="text/javascript"></script>
<script type="text/javascript">
Cufon.replace('.plan-name', { fontFamily: 'Gnuolane Free', hover: true }); 
Cufon.replace('.plan-title', { fontFamily: 'Sony Sketch EF', hover: true }); 
Cufon.replace('.sub-title', { fontFamily: 'Sony Sketch EF', hover: true });
Cufon.replace('.cart-head', { fontFamily: 'Bodonitown', hover: true }); 
Cufon.replace('.cart-title', { fontFamily: 'Enigmatic Regular', hover: true });
Cufon.replace('#steps', { fontFamily: 'Enigmatic Regular', hover: true }); 

</script>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox-basic.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox.css" />
<script type="text/javascript">
/* <![CDATA[ */
	var pageType 	= "Modalbox";
	var webRoot 	= "<?php echo $this->baseUrl();?>";
	var isLocalhost = false;
/* ]]> */
</script>
<script src="<?php echo $this->baseUrl();?>/js/modelbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.modalbox-1.4.0-min.js"></script>
<script type="text/javascript">
	javascript: window.history.forward(1);
</script>


<link href="../../../public/css/site.css" rel="stylesheet" type="text/css">
</head>
<body>
<?php require_once("./header.php");?>
<div id="main">
	<div id="content">
	<h1><?php echo $this->escape($this->title); ?></h1>
	<?php echo $this->layout()->content; ?>
	
	</div>
	<div id="login">
		<div id="leftnav">
<div id="logo_image"><img src="<?php echo $this->baseUrl();?>/images/header_image.png" width="300" height="162">
</div>
<?php echo $this->placeholder('sidebar') ?>
<div id="bannerright">

</div>
</div>
 <div class="right-nav-bottom">
 <?php 
 
$step=1;
if(strstr($_SERVER['HTTP_REFERER'],'PlanList/listplan',true))
    $step=2;
if(strstr($_SERVER['HTTP_REFERER'],'PlanList/compareplans',true))
    $step=2;
if(strstr($_SERVER['HTTP_REFERER'],'UserRegister/adduser',true))
    $step=3; 
if(strstr($_SERVER['HTTP_REFERER'],'Cart/index',true))
    $step=3;
if($_GET['tx']!='')
    $step=4;

 ?>
<div id="steps">
<div class="st-title">Signup Now</div>
<dl>
	<dt <?php if($step==1){echo 'class="selected"';}?>>1</dt>
    <dd>Select Plan
    <?php 
    $SelectedPlan = new Zend_Session_Namespace('SelectedPlan');
    if($SelectedPlan->SelectedPlan <> "")
    {
        echo '('.$SelectedPlan->SelectedPlan.')';
    }
    ?>
    </dd>
    <dt <?php if($step==2){echo 'class="selected"';}?>>2</dt>
    <dd>Registration
    <?php 
    $userfullname = new Zend_Session_Namespace('UserFullName');
    if($userfullname->UserFullName <> "")
    {
    	echo '('. $userfullname->UserFullName.')';
    }
    ?>
    </dd>
    <dt <?php if($step==3){echo 'class="selected"';}?>>3</dt>
    <dd>Payment</dd>
    <dt <?php if($step==4){echo 'class="selected"';}?>>4</dt>
    <dd>Activation</dd>
</dl>
</div>
 </div>
	</div>
  
   
	<div class="clear"></div>
</div>
<div id="mainshadow">
</div>
<?php require_once("./footer.php");?>
</body>
</html>