<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hosted EMR');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>

<link href="<?php echo $this->baseUrl().'/css/user.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/validationEngine.jquery.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid_jui.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/jquery-ui-1.8.4.custom.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/tooltip.css';?>" rel="stylesheet" type="text/css" />


<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.5.1.min.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine-en.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/curvycorners.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jquery.dataTables.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.popupwindow.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jtip.js';?>"></script>

<script type="text/JavaScript">
  window.onload = function() {
    var settings = {
      tl: { radius: 12 },
      tr: { radius: 12 },
      bl: { radius: 12 },
      br: { radius: 12 },
      antiAlias: true
    }

  //  var divObj = document.getElementById("main");
   // curvyCorners(settings, divObj);
    // or, equivalently:
    curvyCorners(settings, '#dashboard');

  }
  var profiles =
	{

		window800:
		{
			height:800,
			width:800,
			status:1
		},

		window200:
		{
			height:200,
			width:200,
			status:1,
			resizable:0
		},

		windowCenter:
		{
			height:300,
			width:400,
			center:1
		},

		windowNotNew:
		{
			height:300,
			width:400,
			center:1,
			createnew:0
		},

		windowCallUnload:
		{
			height:300,
			width:400,
			center:1,
			onUnload:unloadcallback
		},

	};

	function unloadcallback(){
		alert("unloaded");
	};


	$(function()
	{
		$(".popupwindow").popupwindow(profiles);
	});
</script>
</head>
<body>
<?php require_once("./header.php");?>
<div id="main">
  <div id="user">
    <div class="content" style="width:1000px;"> <?php echo $this->layout()->content; ?> </div>
      
  </div>
  <div class="clear"></div>
</div>
<?php require_once("./footer.php");?>
</body>
</html>