<?php
$this->headMeta()->appendHttpEquiv('Content-Type', 'text/html;charset=utf-8');
$this->headTitle()->setSeparator(' - ');
$this->headTitle('Hosted EMR');
echo $this->doctype(); 
?>
<html xmlns="http://www.w3.org/1999/xhtml" xml:lang="en" lang="en">
<head>
<meta http-equiv="X-UA-Compatible" content="IE=EmulateIE8" >
<?php echo $this->headMeta(); ?>
<?php echo $this->headTitle(); ?>

<link href="<?php echo $this->baseUrl().'/css/user.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/validationEngine.jquery.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/grid_jui.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/jquery-ui-1.8.4.custom.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->baseUrl().'/css/tooltip.css';?>" rel="stylesheet" type="text/css" />


<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery-1.5.1.min.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/jquery/jquery.validationEngine-en.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/curvycorners.js';?>"></script>
<script language="javascript" src="<?php echo $this->baseUrl().'/js/jtip.js';?>"></script>

<script src="<?php echo $this->baseUrl()?>/js/cufon-yui.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/gnuolane.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/sony-sketch-ef.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/bodonitown.cufonfonts.js" type="text/javascript"></script>
<script src="<?php echo $this->baseUrl()?>/js/enigmatic.cufonfonts.js" type="text/javascript"></script>
<script type="text/javascript">
Cufon.replace('.plan-name', { fontFamily: 'Gnuolane Free', hover: true }); 
Cufon.replace('.plan-title', { fontFamily: 'Sony Sketch EF', hover: true }); 
Cufon.replace('.sub-title', { fontFamily: 'Sony Sketch EF', hover: true });
Cufon.replace('.cart-head', { fontFamily: 'Bodonitown', hover: true }); 
Cufon.replace('.cart-title', { fontFamily: 'Enigmatic Regular', hover: true });

</script>
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox-basic.css" />
<link rel="stylesheet" type="text/css" media="all" href="<?php echo $this->baseUrl();?>/css/jquery.modalbox.css" />
<script type="text/javascript">
/* <![CDATA[ */
	var pageType 	= "Modalbox";
	var webRoot 	= "<?php echo $this->baseUrl();?>";
	var isLocalhost = false;
/* ]]> */
</script>
<script src="<?php echo $this->baseUrl();?>/js/modelbox.js"></script>
<script type="text/javascript" src="<?php echo $this->baseUrl();?>/js/jquery.modalbox-1.4.0-min.js"></script>

<script type="text/javascript">
	//javascript: window.history.forward(1);
</script>
<script type="text/JavaScript">
 

	$(function()
	{
		$(".popupwindow").popupwindow(profiles);
	});
</script>
</head>
<body>
<?php require_once("./header.php");?>
<div id="main">
  <div id="user">
    <div class="content"> <?php echo $this->layout()->content; ?> </div>
      <div class="usermenu">
  <!-- Right Side Content-->
   <div id="dashboard">
        <table width="100%" border="0" cellspacing="0" cellpadding="0">
          <tr>
            <td>
            <?php 
            $sess = new Zend_Session_Namespace('user');
            $hf_id=$sess->hf_id;
            if($this->checkaclresource('user','Profile',$hf_id))
            {
            ?>
            <fieldset class="frameset-profile">
    <legend>Profile:</legend>
<table border="0" cellspacing="3" cellpadding="0">
  <tr>
    <td>
    <?php
   
	if($this->checkacl('user','Profile','index',$hf_id))	
	{
	 ?>
	
     <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Profile','action'=>'index'),0,true);?>">
    <img src="<?php echo $this->baseUrl();?>/images/Profile.png" width="32" height="32" alt="Profile" title="Update Profile" />
    </a>
    <?php }?>
    </td>
    <td>
    <?php if($this->checkacl('user','Changepassword','index',$hf_id)){?>
     <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Changepassword','action'=>'index'),0,true);?>">
    <img src="<?php echo $this->baseUrl();?>/images/change_password.png" width="32" height="32" alt="Change Password" title="Change Password" />
    </a>
    <?php }?>
    </td>
    <td> <!--  a href="<?php echo $this->url(array('module'=>'user','controller'=>'Changepassword','action'=>'index'),0,true);?>">
    <img src="<?php echo $this->baseUrl();?>/images/users.png" width="32" height="32" alt="Additional Users" title="Additional Users" />
    </a--></td>
  </tr>
</table>
  </fieldset>
  <?php }?>
            </td>
          </tr>
          <tr>
            <td>
            <?php  if($this->checkaclresource('user','Plan',$hf_id)){?>
            <fieldset class="frameset-profile">
        <legend>Plan Status:</legend>
  <table width="100%" border="0" cellspacing="3" cellpadding="0">
    <tr>
      <td width="18%">
      <?php if($this->checkacl('user','Plan','index',$hf_id)){?>
      <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Plan','action'=>'index'),0,true);?>">
      <img src="<?php echo $this->baseUrl();?>/images/plan.png" width="32" height="32" alt="Plan Details" title="Plan Details">
      </a>
      <?php }?>
      </td>
      <td width="72%">
      <?php if($this->checkacl('user','Products','index',$hf_id)){?>
      <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Products','action'=>'index'),0,true);?>">
      <img src="<?php echo $this->baseUrl();?>/images/product_big.png" width="32" height="32" alt="Additional Products" title="Additional Products">
      </a>
      <?php }?>
      </td>
      <td width="10%">&nbsp;</td>
      </tr>
    </table>
      </fieldset>
<?php }?>
            </td>
          </tr>
          <tr>
            <td>
            <?php  if($this->checkaclresource('user','Invoice',$hf_id)){?>
              <fieldset class="frameset-profile">
        <legend>Invoices:</legend>
  <table border="0" cellspacing="3" cellpadding="0">
    <tr>
      <td>
      <?php if($this->checkacl('user','Invoice','paidinvoice',$hf_id)){?>
      <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Invoice','action'=>'paidinvoice'),0,true);?>">
      <img src="<?php echo $this->baseUrl();?>/images/invoice.png" width="32" height="32" alt="Paid Invoices" title="Paid Invoices" />
      </a>
      <?php }?>
      </td>
      <td>
      <?php if($this->checkacl('user','Invoice','outstandinginvoice',$hf_id)){?>
      <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Invoice','action'=>'outstandinginvoice'),0,true);?>">
      <img src="<?php echo $this->baseUrl();?>/images/Outstanding_invoice.png" width="32" height="32" alt="Outstanding Invoices" title="Outstanding Invoices" />
      </a>
      <?php }?>
      </td>
      <td>
      <?php if($this->checkacl('user','Invoice','ledgerbalance',$hf_id)){?>
      <a href="<?php echo $this->url(array('module'=>'user','controller'=>'Invoice','action'=>'ledgerbalance'),0,true);?>">
      <img src="<?php echo $this->baseUrl();?>/images/ledger.png" width="32" height="32" alt="Ledger Balance" title="Ledger Balance">
      </a>
      <?php }?>
      </td>
      </tr>
    <tr>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
      <td>&nbsp;</td>
    </tr>
    </table>
      </fieldset>
		<?php }?>
            </td>
          </tr>
          <tr>
            <td>&nbsp;</td>
          </tr>
        </table>
      
      </div>
  <!-- Right Side Content End -->
    </div>
  </div>
  <div class="clear"></div>
</div>
<?php require_once("./footer.php");?>
</body>
</html>