<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#productprice").validationEngine();
            });
</script>


<div id="right_panel">
  <form id="productprice" name="productprice" method="post" action="">
  <input type="hidden" name="idproducts" value="<?php echo $this->Ecode($this->productprice['idproducts']);?>" />
  <input type="hidden" name="idproduct_feature" value="<?php echo $this->Ecode($this->productprice['idproduct_feature']);?>" />
    <table width="100%" border="0" cellspacing="0" cellpadding="4">
      <tr>
        <td colspan="3" class="list-table-header shadow">Update Cost</td>
      </tr>
      <tr>
        <td width="19%" class="label line">Product Name</td>
        <td width="1%">:</td>
        <td width="80%" class="label line">&nbsp;<?php echo $this->productname;?></td>
      </tr>
      <tr>
        <td class="label line">Product Cost</td>
        <td>:</td>
        <td class="label line">$
          <label for="cost"></label>
        <input type="text" name="cost" id="cost" value="<?php echo $this->productprice['cost']?>" /></td>
      </tr>
      <tr>
        <td class="label line">User Range (From)</td>
        <td>:</td>
        <td class="label line"><input type="text" name="user_from" id="user_from" value="<?php echo $this->productprice['user_from']?>"/></td>
      </tr>
      <tr>
        <td class="label line">User Range (To)</td>
        <td>:</td>
        <td class="label line"><input type="text" name="user_to" id="user_to" value="<?php echo $this->productprice['user_to']?>" /></td>
      </tr>
      <tr>
        <td class="label line">Listing Order</td>
        <td>:</td>
        <td class="label line">
        <input type="text" name="sortorder" id="sortorder" value="<?php echo $this->productprice['sortorder']?>" class="validate[required],custom[integer]" /></td>
      </tr>
      <tr>
        <td class="label line">Status</td>
        <td>:</td>
        <td class="label line">
          <p>
            <label>
              <input name="status" type="radio" id="status_0" value="1"  <?php if($this->productprice['status']=="1")echo 'checked="checked"';?> />
              Active</label>
            <br />
            <label>
              <input type="radio" name="status" value="0" id="status_1"  <?php if($this->productprice['status']=="0")echo 'checked="checked"';?>/>
              Disable</label>
            <br />
        </p></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td><input type="submit" name="button" id="button" value="Update" class="shadow" /></td>
      </tr>
    </table>
  </form>
</div>
<div class="clear"></div>
<p>&nbsp;</p>
<p>&nbsp;</p><p>&nbsp;</p>