	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/jquery/db/themes/base/jquery.ui.all.css">
	<script src="<?php echo $this->baseUrl();?>/jquery/db/external/jquery.bgiframe-2.1.2.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.core.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.widget.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.mouse.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.button.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.draggable.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.position.js"></script>
	<script src="<?php echo $this->baseUrl();?>/jquery/db/ui/jquery.ui.dialog.js"></script>
	<link rel="stylesheet" href="<?php echo $this->baseUrl();?>/jquery/db/demo/demos.css">
	
	<script>
	$(function() {
		$("#dialog-confirm").addClass("hidevisible");  
		});
	
	
	function del(delid,idproducts)
	{
		$(function() {
		$( "#dialog-confirm" ).addClass("shovisible");
		$( "#dialog:ui-dialog" ).dialog( "destroy" );
			$( "#dialog-confirm" ).dialog({
				resizable: false,
				height:180,
				modal: true,
				buttons: {
					"Delete all items": function() {
						$( this ).dialog( "close" );
						window.location.href="<?php echo $this->baseUrl();?>/Admin/Productprice/delete/id/"+delid+"/idproducts/"+idproducts+"";
					},
					Cancel: function() {
						$( this ).dialog( "close" );
					}
				}
			});
		});
	}
	
</script>
<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<div id="right_panel">
 <div id="dialog-confirm" title="Delete Record?">
	<p><span class="ui-icon ui-icon-alert" style="float:left; margin:0 7px 20px 0;"></span>The item will be permanently deleted and cannot be recovered. Are you sure?</p>
</div>

<div class="addnew">
    <?php echo '<a href="'.$this->url(array('module'=>'Admin','controller'=>'Productprice','action'=>'add','idproducts'=>$this->idproducts),0,true).'" class="add">';?>
    Add New Cost
    <?php echo "</a>";?>
</div>
    
<table width="100%" border="0" cellspacing="0" cellpadding="0" id="grid">
  <thead>
  <tr>
    <td height="20" class="invoice-table-title b table-head-bg white" align="center">#</td>
    <td class="invoice-table-title b table-head-bg">Product Name</td>
    <td class="invoice-table-title b table-head-bg" align="right">Product Cost (in $)</td>
    <td align="center" nowrap="nowrap" class="invoice-table-title b table-head-bg">User Range</td>
    <td class="invoice-table-title b table-head-bg" align="center">Status</td>
    <td class="invoice-table-title b table-head-bg" align="center">Added Date</td>
    <td class="invoice-table-title b table-head-bg"></td>
  </tr>
  </thead>
  <tbody>
  <?php 
   $sino=1;
  //$currency = new Zend_Currency();
  foreach($this->productprice as $productprice)
  {
  ?>
  <tr>
    <td height="22" class="normal-text  line" align="center"><?php echo $sino;?>.</td>
    <td class="normal-text line"><?php echo $this->productname;?></td>
    <td class="normal-text line" align="right"><?php echo $productprice['cost'];?></td>
    <td class="normal-text line" align="center"><?php echo $productprice['user_from'];?> to <?php echo $productprice['user_to'];?></td>
    <td class="normal-text line" align="center"><?php
    echo($productprice['status'])?'<img src="'.$this->baseUrl().'/images/active.png" alt="Active" title="Active"/>':'<img src="'.$this->baseUrl().'/images/disable.png" alt="Disabled" title="Disabled"/>';
    ?></td>
    <td class="normal-text line" align="center"><?php echo  $this->Disdate($productprice['added_date'])?></td>

    <td class="normal-text line" align="center">
  <?php   
    
    echo '<a href="'.$this->url(array('module'=>'Admin','controller'=>'Productprice','action'=>'edit', 'idproduct_feature'=>$this->Ecode($productprice['idproduct_feature']),'idproducts'=>$this->Ecode($productprice['idproducts'])),0,true).'">';
    echo "<img src='".$this->baseUrl()."/images/edit.png' alt='Edit' title='Edit'  style='cursor:pointer;' />";
    echo '</a>&nbsp;';
       	echo "<img src='".$this->baseUrl()."/images/delete.gif' alt='Delete' title='Delete' onClick='del(".$productprice['idproduct_feature'].",".$productprice['idproducts'].")'   style='cursor:pointer;'/>";
    ?>
    </td>
  </tr>
  <?php 
  $sino = ++$sino;
  }
  ?>
  </tbody>
</table>
  </div>
 <script type="text/javascript">
                //<![CDATA[
 $(document).ready(function() {
	    oTable = $('#grid').dataTable({
	        "bJQueryUI": true,
	        "sPaginationType": "full_numbers"
	    });
	} );
                //]]>
                </script>