<table width="100%" border="0" cellspacing="2" cellpadding="2">
    <tr>
      <td colspan="4" class="plan-title shadow"><?php echo $this->planname['plan_name'];?> (Provider : <?php echo $this->providerno;?>)</td>
    </tr>
    <tr>
      <td colspan="4" class="normal-text">This Plan includes following packages :</td>
    </tr>
    <tr>
      <td width="3%" align="center" class="table-head shadow">#</td>
      <td width="73%" class="table-head shadow">Package Name</td>
      <td width="24%" align="right" class="table-head shadow">Onetime Fee</td>
      <td width="24%" align="right" class="table-head shadow">Cost</td>
    </tr>
    <?php
    $plancost=0;
    $setupfee=0;
    $sino=1; 
    foreach($this->productdetails as $productdtd)
    {
    ?>
    <tr>
      <td align="center" valign="top" class="normal-text shadowlight"><?php echo $sino;?>.</td>
      <td class="normal-text shadowlight"><span class="product"><?php echo $productdtd['product_name'];?>
      </span><br />
        <strong>Features : </strong>
        <p><?php echo $productdtd['product_feature'];?></p></td>
      <td align="right" valign="top" class="normal-text shadowlight">$ <?php echo $productdtd['setup_fee'];?></td>
      <td align="right" valign="top" class="normal-text shadowlight">$ <?php echo $productdtd['cost'];?></td>
    </tr>
   
    <?php 
    	$setupfee=$setupfee + $productdtd['setup_fee'];
    	if($productdtd['cost']=="")
    	    $productdtd['cost']=0;
    	$plancost = $plancost + $productdtd['cost'];
    $sino = $sino + 1;
    }
    ?>
     <tr>
      <td align="center" valign="top" class="normal-text shadowlight">&nbsp;</td>
      <td class="table-head shadowlight">Plan Amount :</td>
      <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight">$ <?php echo $setupfee;?></td>
      <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight">$ <?php echo $plancost;?></td>
    </tr>
     <tr>
       <td align="center" valign="top" class="normal-text shadowlight">&nbsp;</td>
       <td class="table-head shadowlight b">Total Plan Cost :</td>
       <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight">&nbsp;</td>
       <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight b">$ <?php echo $setupfee + $plancost; ?></td>
     </tr>
  </table>
