<table width="680px;" border="0" cellspacing="2" cellpadding="2" align=center>
  <?php 
  if($this->cms)
  {
  		echo '<div class="cms">';
		if(!$this->cms['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cms['cms_details'];
	echo '</div>';
  }
?>
 <?php 
 echo $this->allplans;
 ?>
  
</table>
  <?php 
  if($this->cmssupport)
  {
  		echo '<div class="cms">';
		if(!$this->cmssupport['cms_title']=="")
		{
    		echo '<span>'.$this->cmssupport['cms_title'].'</span><br/>';
		}	
	echo $this->cmssupport['cms_details'];
	echo '</div>';
  }
?>