<?php $this->placeholder('sidebar')->captureStart() ?>
<script language="javascript">
function updateprice(pval)
{
	provider = parseInt(pval);
	document.getElementById("apid").value=provider;
	
	if(document.getElementById("apid").value==0)
	{
		document.getElementById("checkout").innerHTML="<span class='error'>Please select the number of providers to proceed checkout</span>";
		
		document.getElementById("pcost").value = 0;
		document.getElementById("totalfee").value = 0;
		document.getElementById("totalamount").innerHTML = "$ 0.00";
		
		document.getElementById("setupfee").innerHTML="$ 0.00";
		document.getElementById("gtotal").innerHTML = "$ 0.00";
	}
	else
	{
		document.getElementById("checkout").innerHTML='<input name="" type="submit" value="Proceed to Registration" />';	
		
		bundle_discount_type = parseFloat(document.getElementById("bundle_discount_type").value);
		bundle_discount_per_cost = parseFloat(document.getElementById("bundle_discount_per_cost").value);
		bundle_discount_per_setup = parseFloat(document.getElementById("bundle_discount_per_setup").value);
		
		
		VariableProductCostTotal = parseFloat(document.getElementById("VariableProductCostTotal").value);
		VariableProductSetupFeeTotal = parseFloat(document.getElementById("VariableProductSetupFeeTotal").value);
		
		FixedProductCostTotal = parseFloat(document.getElementById("FixedProductCostTotal").value);
		FixedProductSetupFeeTotal = parseFloat(document.getElementById("FixedProductSetupFeeTotal").value);
	
		if(bundle_discount_type==1) // % wise
		{
			if(VariableProductCostTotal>0)
			{
					VariableProductCostTotal = VariableProductCostTotal * provider;
					VariableProductCostTotal = VariableProductCostTotal - ((VariableProductCostTotal * bundle_discount_per_cost)/100);
			}
			else
			{
					VariableProductCostTotal=0;
			}
			if(VariableProductSetupFeeTotal>0)
			{
				VariableProductSetupFeeTotal = VariableProductSetupFeeTotal * provider;
				VariableProductSetupFeeTotal = VariableProductSetupFeeTotal - ((VariableProductSetupFeeTotal * bundle_discount_per_setup)/100);
			}
			else
			{
				VariableProductSetupFeeTotal=0;	
			}
			FixedProductSetupFeeTotal = FixedProductSetupFeeTotal - ((FixedProductSetupFeeTotal * bundle_discount_per_setup)/100);
		}
		if(bundle_discount_type==2) // Flat discount
		{
			if(VariableProductCostTotal>0)
			{
				VariableProductCostTotal = (VariableProductCostTotal * provider) -  (bundle_discount_per_cost * provider);
			}
			else
			{
				VariableProductCostTotal=0;
			}
			if(VariableProductSetupFeeTotal > 0)
			{
				VariableProductSetupFeeTotal = (VariableProductSetupFeeTotal * provider) - (bundle_discount_per_setup * provider);
			}
			else
			{
				VariableProductSetupFeeTotal=0;
			}
			
			FixedProductSetupFeeTotal = (FixedProductSetupFeeTotal) - (bundle_discount_per_setup * provider);
			
		}
		TotalOneTimeFee = FixedProductSetupFeeTotal + VariableProductSetupFeeTotal;
		TotalVariableFee = FixedProductCostTotal + VariableProductCostTotal;
		pcost = VariableProductCostTotal + FixedProductCostTotal;
		setupfee = VariableProductSetupFeeTotal + FixedProductSetupFeeTotal;
		totalfee = pcost + setupfee;
		
		document.getElementById("pcost").value = pcost;
		document.getElementById("totalfee").value = totalfee;
		document.getElementById("totalamount").innerHTML = "$ "+pcost+"";
	
		if($("#setupfee").length) {
		document.getElementById("setupfee").innerHTML="$ "+setupfee+"";
		}

		if($("#gtotal").length) {
		document.getElementById("gtotal").innerHTML = "$ "+totalfee+"";
		}
	}
	$('html,body').animate({scrollTop: $("#checkout").offset().top},'slow');
	
	
	

}

$(document).ready(function() {
  var opts = {collapseTimer: 4000};

  $.each(['beforeExpand', 'afterExpand', 'onCollapse'], function(i, callback) {
    opts[callback] = function(byUser) {
      var by, msg = '<div class="success">' + callback;

      if (callback == 'onCollapse') {
        msg += ' (' + (byUser ? 'user' : 'timer') + ')';
      }
      msg += '</div>';

      $(this).parent().parent().append(msg)
    }
  });


  $('div.features').expander({
    slicePoint: 40,
    widow: 2,
    expandSpeed: 0,
	expandEffect: 'show',
    userCollapseText: '[^]'
  });


});

</script>
<link href="../../../../public/css/site.css" rel="stylesheet" type="text/css" />
   <?php 
  if($this->cms)
  {
  		echo '<div class="cms">';
		if(!$this->cms['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cms['cms_details'];
	echo '</div>';
  }
?>
<div class="leftpanel">
<form method="post" action="<?php echo $this->baseUrl();?>/UserRegister/adduser/">
<input type="hidden" name="_sec" value="plan">
 <table width="100%" border="0" cellspacing="2" cellpadding="2">
    <tr>
      <td colspan="4" class="plan-title shadow"><?php echo $this->planname['hp_name'];?></td>
    </tr>
    <tr>
      <td colspan="2" nowrap="nowrap" class="normal-text b"><p>Please select the  number of providers using this system</p></td>
      <td colspan="2" class="normal-text"><select name="provider" id="provider" onchange="updateprice(this.value)">
        <?php 
      for($i=0;$i<=100;$i++)
      {
          echo "<option value=$i>$i</option>";
      }
      ?>
      </select></td>
      </tr>
    <tr>
      <td colspan="4" class="normal-text">This Plan includes following packages :</td>
    </tr>
    <tr>
      <td width="3%" align="center" class="table-head shadow">#</td>
      <td width="73%" class="table-head shadow">Package Name</td>
      <?php
	  if($this->planname['bundle_setup_cost']!=0){
	  ?>
      <td width="24%" align="right" nowrap="nowrap" class="table-head shadow">Onetime Fee&nbsp;</td>
      <?php } ?>
      <td width="24%" align="right"  nowrap="nowrap" class="table-head shadow">Recurring Fee (monthly)</td>
    </tr>
    <?php
    $plancost=0;
	$setupfee=0;
    $sino=1; 
    
    $currency = new Zend_Currency('en_US');
    
    foreach($this->productdetails as $productdtd)
    {
        

    ?>
    <tr>
      <td align="center" valign="top" class="normal-text shadowlight"><?php echo $sino;?>.</td>
      <td class="normal-text shadowlight"><span class="product"><?php echo $productdtd['product_name'];?>
      </span><br />
        <div class="features"><?php echo $productdtd['product_feature'];?></div></td>
       <?php
	  if($this->planname['bundle_setup_cost']!=0){
	  ?>
      <td align="right" valign="top" class="normal-text shadowlight"><?php echo($productdtd['setup_fee']=="0")?'$0.00':$currency->toCurrency($productdtd['setup_fee']);?></td>
      <?php } ?>
      <td align="right" valign="top" class="normal-text shadowlight"><?php echo($productdtd['cost']=="0")?'$0.00':$currency->toCurrency($productdtd['cost']);?></td>
    </tr>
   <?php 
   
	   if($productdtd['cost']=="")
	   	$productdtd['cost']=0;
	   $setupfee = $setupfee + $productdtd['setup_fee'];
	   $plancost = $plancost + $productdtd['cost'];
  
        
   
    	
    $sino = $sino + 1;
    }
	$gtotal = $setupfee + $plancost;
	 if(($setupfee > $this->planname['bundle_setup_cost'])||($plancost > $this->planname['bundle_cost']))
	 {
    ?>
     <tr>
       <td align="center" valign="top" class="normal-text shadowlight">&nbsp;</td>
       <td align="right" class="table-head shadowlight">List Price</td>
       <?php  if($this->planname['bundle_setup_cost']!=0){?>
       <td align="right" valign="top" class="table-head shadowlight">
       <?php
	   if($setupfee > $this->planname['bundle_setup_cost'])
	   {
			echo '<span class="strike">'.$currency->toCurrency($setupfee).'</span>';
	   }
	    if($setupfee = $this->planname['bundle_setup_cost'])
	   {
			echo $currency->toCurrency($setupfee);
	   }
	   ?>
       </td>
       <?php }?>
       <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight" id="monthlyfee2">
        <?php
	   if($plancost > $this->planname['bundle_cost'])
	   {
			echo '<span class="strike">'.$currency->toCurrency($plancost).'</span>';
	   }
	   ?>
       </td>
     </tr>
     <?php
	 }
	 ?>
     <tr>
      <td align="center" valign="top" class="normal-text shadowlight">&nbsp;</td>
      <td align="right" class="table-head shadowlight">
       <input type="hidden" name="pid" value="<?php echo $this->ecode($this->pid);?>" />
       <input type="hidden" name="bundle_discount_type" id="bundle_discount_type" value="<?php echo $this->planname['bundle_discount_type'];?>" />
       <input type="hidden" name="bundle_discount_per_cost" id="bundle_discount_per_cost" value="<?php echo $this->planname['bundle_discount_per_cost'];?>" />
       <input type="hidden" name="bundle_discount_per_setup" id="bundle_discount_per_setup" value="<?php echo $this->planname['bundle_discount_per_setup'];?>" />
       
       <input type="hidden" name="VariableProductCostTotal" id="VariableProductCostTotal" value="<?php echo $this->VariableProductCostTotal;?>" />
       <input type="hidden" name="FixedProductCostTotal" id="FixedProductCostTotal" value="<?php echo $this->FixedProductCostTotal;?>" />
       <input type="hidden" name="VariableProductSetupFeeTotal" id="VariableProductSetupFeeTotal" value="<?php echo $this->VariableProductSetupFeeTotal;?>" />
       <input type="hidden" name="FixedProductSetupFeeTotal" id="FixedProductSetupFeeTotal" value="<?php echo $this->FixedProductSetupFeeTotal; ?>" />
       
       
      <input type="hidden" name="pcost" id="pcost" <?php echo $this->planname['bundle_cost']*0;?> />
      <input type="hidden" name="totalfee" id="totalfee" <?php echo $this->planname['bundle_setup_cost']*0;?> />
      <input type="hidden" name="apid" id="apid" value="0" />Plan Price
      </td>
        <?php
	  if($this->planname['bundle_setup_cost']!=0){
	  ?>
      <td align="right" valign="top" class="table-head shadowlight"> <?php echo $currency->toCurrency($this->planname['bundle_setup_cost']);?></td>
      <?php } ?>
      <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight" id="monthlyfee"><?php echo $currency->toCurrency($this->planname['bundle_cost']);?></td>
    </tr>
      <?php
	  $colspan=2;
	  if($this->planname['bundle_setup_cost']!=0){
		  $colspan=3;
	  ?>
     <tr>
       <td colspan="3" align="right" valign="top" class="normal-text shadowlight">Total Onetime Fee :
        </td>
       <td align="right" valign="top" class="normal-text shadowlight" id="setupfee"> <?php echo $currency->toCurrency($this->planname['bundle_setup_cost']*0);?></td>
     </tr>
     <?php } ?>
     <tr>
       <td colspan="<?php echo  $colspan;?>" align="right" valign="top" class="normal-text shadowlight">Total Monthly Recurring Fee:</td>
       <td align="right" valign="top" class="normal-text shadowlight" id="totalamount"> <?php echo $currency->toCurrency($this->planname['bundle_cost']*0);?></td>
     </tr>
     <tr>
       <td colspan="<?php echo  $colspan;?>" align="right" valign="top" class="normal-text shadowlight"><strong>Gross Amount :</strong></td>
       <td align="right" valign="top" class="normal-text shadowlight b" id="gtotal"> <?php echo $currency->toCurrency(($this->planname['bundle_cost']+$this->planname['bundle_setup_cost'])*0);?></td>
     </tr>
     <tr>
      <td colspan="4" align="right" valign="top" id="checkout">
       <!-- <a href="<?php echo $this->url(array('controller'=>'UserRegister','action'=>'adduser', 'id'=>$this->ecode($this->pid)));?>" class="plan-register">Proceed To Registration</a>-->        <input name="" type="submit" value="Proceed to Registration" />     </td>
    </tr>
  </table>
  </form>
</div>
<script language="javascript" type="text/javascript">
if(document.getElementById("apid").value==0)
{
	document.getElementById("checkout").innerHTML="<span class='error'>Please select the number of providers to proceed checkout</span>";
}
else
{
	document.getElementById("checkout").innerHTML='<input name="" type="submit" value="Proceed to Registration" />';	
}
</script>


