<?php $this->placeholder('sidebar')->captureStart() ?>
<script language="javascript">
function updateprice(pval)
{
	
	pprovider = parseInt(pval);

	document.getElementById("apid").value=pval;
	
	if(document.getElementById("apid").value==0)
	{
		document.getElementById("checkout").disabled=true;
		document.getElementById("provider").style.color="#F00";
		document.getElementById("checkout").style.color="#D8D8D8";

		document.getElementById("gtotal").innerHTML = "$ 0.00";
		document.getElementById("pcost").value = 0;
		document.getElementById("totalfee").value = 0;
		document.getElementById("totalamount").innerHTML = "$ 0.00";
		
		document.getElementById("setupfee").innerHTML="$ 0.00";
		document.getElementById("gtotal").innerHTML = "$ 0.00";
	}
	else
	{
		
		document.getElementById("checkout").disabled=false;
		document.getElementById("provider").style.color="#373737";
		document.getElementById("checkout").style.color="#fff";
		
		bundle_discount_type = parseFloat(document.getElementById("bundle_discount_type").value);
		bundle_discount_per_cost = parseFloat(document.getElementById("bundle_discount_per_cost").value);
		bundle_discount_per_setup = parseFloat(document.getElementById("bundle_discount_per_setup").value);
		
		
		VariableProductCostTotal = parseFloat(document.getElementById("VariableProductCostTotal").value);
		VariableProductSetupFeeTotal = parseFloat(document.getElementById("VariableProductSetupFeeTotal").value);
		
		FixedProductCostTotal = parseFloat(document.getElementById("FixedProductCostTotal").value);
		FixedProductSetupFeeTotal = parseFloat(document.getElementById("FixedProductSetupFeeTotal").value);
		
		if(bundle_discount_type==1) // % wise
		{
			if(VariableProductCostTotal>0)
			{
					VariableProductCostTotal = VariableProductCostTotal * pprovider;
					VariableProductCostTotal = VariableProductCostTotal - ((VariableProductCostTotal * bundle_discount_per_cost)/100);
			}
			else
			{
					VariableProductCostTotal=0;
			}
			if(VariableProductSetupFeeTotal>0)
			{
				VariableProductSetupFeeTotal = VariableProductSetupFeeTotal * pprovider;
				VariableProductSetupFeeTotal = VariableProductSetupFeeTotal - ((VariableProductSetupFeeTotal * bundle_discount_per_setup)/100);
			}
			else
			{
				VariableProductSetupFeeTotal=0;	
			}
			FixedProductSetupFeeTotal = FixedProductSetupFeeTotal - ((FixedProductSetupFeeTotal * bundle_discount_per_setup)/100);
		}
		
		if(bundle_discount_type==2) // Flat discount
		{
			if(VariableProductCostTotal>0)
			{
				VariableProductCostTotal = (VariableProductCostTotal * pprovider) -  (bundle_discount_per_cost * pprovider);
			}
			else
			{
				VariableProductCostTotal=0;
			}
			if(VariableProductSetupFeeTotal > 0)
			{
				VariableProductSetupFeeTotal = (VariableProductSetupFeeTotal * pprovider) - (bundle_discount_per_setup * pprovider);
			}
			else
			{
				VariableProductSetupFeeTotal=0;
			}

			
			FixedProductSetupFeeTotal = (FixedProductSetupFeeTotal) - (bundle_discount_per_setup * pprovider);
			
			
		}

		
		TotalOneTimeFee = FixedProductSetupFeeTotal + VariableProductSetupFeeTotal;
		
		TotalVariableFee = FixedProductCostTotal + VariableProductCostTotal;
		
		pcost = VariableProductCostTotal + FixedProductCostTotal;

		
		setupfeee = parseFloat(VariableProductSetupFeeTotal) + parseFloat(FixedProductSetupFeeTotal);
		
		totalfee = pcost + setupfeee;
		
		document.getElementById("pcost").value = pcost;
		document.getElementById("totalfee").value = totalfee;
		document.getElementById("totalamount").innerHTML = "$ "+pcost+"";
		
		if($("#setupfee").length) {
		document.getElementById("setupfee").innerHTML="$ "+setupfeee+"";
		}

		if($("#gtotal").length) {
		document.getElementById("gtotal").innerHTML = "$ "+totalfee+"";
		}
	}
	$('html,body').animate({scrollTop: $("#checkout").offset().top},'slow');
	
	
	

}

$(document).ready(function() {
  $('div.features').expander({
    slicePoint: 40,
    widow: 2,
    expandSpeed: 0,
	expandEffect: 'show',
    userCollapseText: '<img src=<?php echo $this->baseUrl();?>/images/plus.gif>'
  });
});

</script>
   <?php 
    $sess = new Zend_Session_Namespace('user');
  if($this->cms)
  {
  		echo '<div class="cms">';
		if(!$this->cms['cms_title']=="")
		{
    		echo '<span>'.$this->cms['cms_title'].'</span><br/>';
		}	
	echo $this->cms['cms_details'];
	echo '</div>';
  }
?>

   
 
<div class="leftpanel">

 <?php
	  if($sess->step=="compare")
	  {
	  ?>
<form method="post" action="<?php echo $this->baseUrl();?>/UserRegister/usernoplan/">
<?php
	  }
	  else
	  {
	  ?>

<form method="post" action="<?php echo $this->baseUrl();?>/UserRegister/adduser/">
<?php
}
?>
<input type="hidden" name="_sec" value="plan">
 <table width="100%" border="0" cellspacing="2" cellpadding="2">
    <tr>
      <td colspan="4" class="plan-title shadow"><?php echo $this->planname['hp_name'];?></td>
    </tr>
    <tr>
      <td colspan="4" class="normal-text">This Plan includes following packages :</td>
    </tr>
    <tr>
      <td width="3%" align="center" class="table-head shadow">#</td>
      <td width="73%" class="table-head shadow">Package Name</td>
      <?php
	  if($this->planname['bundle_setup_cost']!=0){
	  ?>
      <td width="24%" align="right" nowrap="nowrap" class="table-head shadow">Onetime Fee&nbsp;</td>
      <?php } ?>
      <td width="24%" align="right"  nowrap="nowrap" class="table-head shadow">Recurring Fee (monthly)</td>
    </tr>
    <?php
    $plancost=0;
	$setupfee=0;
    $sino=1; 
    
    $currency = new Zend_Currency('en_US');
    
    foreach($this->productdetails as $productdtd)
    {
        

    ?>
    <tr>
      <td align="center" valign="top" class="normal-text shadowlight"><?php echo $sino;?>.</td>
      <td class="normal-text shadowlight"><span class="product">
	 <?php
     echo  '<a class="openmodalbox" href="javascript:void(0);"	rel="ajax: '.$this->baseUrl().'/user/Products/productfeature/id/'.base64_encode($productdtd['idproducts']).'">'.$productdtd['product_name'].'</a>';
	  ?>
      </span></td>
       <?php
	  if($this->planname['bundle_setup_cost']!=0){
	  ?>
      <td align="right" valign="top" class="normal-text shadowlight"><?php echo($productdtd['setup_fee']=="0")?'$0.00':$currency->toCurrency($productdtd['setup_fee']);?></td>
      <?php } ?>
      <td align="right" valign="top" class="normal-text shadowlight"><?php echo($productdtd['cost']=="0")?'$0.00':$currency->toCurrency($productdtd['cost']);?></td>
    </tr>
   <?php 
   
	   if($productdtd['cost']=="")
	   	$productdtd['cost']=0;
	   $setupfee = $setupfee + $productdtd['setup_fee'];
	   $plancost = $plancost + $productdtd['cost'];
  
        
   
    	
    $sino = $sino + 1;
    }
	$gtotal = $setupfee + $plancost;
	 if(($setupfee > $this->planname['bundle_setup_cost'])||($plancost > $this->planname['bundle_cost']))
	 {
    ?>
     <tr>
       <td colspan="2" align="right" valign="top" class="table-head shadowlight">List Price :</td>
       <?php  if($this->planname['bundle_setup_cost']!=0){?>
       <td align="right" valign="top" class="table-head shadowlight">
       <?php
	   if($setupfee > $this->planname['bundle_setup_cost'])
	   {
			echo '<span class="strike">'.$currency->toCurrency($setupfee).'</span>';
	   }
	    if($setupfee = $this->planname['bundle_setup_cost'])
	   {
			echo $currency->toCurrency($setupfee);
	   }
	   ?>
       </td>
       <?php }?>
       <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight" id="monthlyfee2">
        <?php
	   if($plancost > $this->planname['bundle_cost'])
	   {
			echo '<span class="strike">'.$currency->toCurrency($plancost).'</span>';
	   }
	   ?>
       </td>
     </tr>
     <?php
	 }
	 ?>
     <tr>
      <td colspan="2" align="right" valign="top" class="table-head shadowlight">
        <input type="hidden" name="pid" value="<?php echo $this->ecode($this->pid);?>" />
        <input type="hidden" name="bundle_discount_type" id="bundle_discount_type" value="<?php echo $this->planname['bundle_discount_type'];?>" />
        <input type="hidden" name="bundle_discount_per_cost" id="bundle_discount_per_cost" value="<?php echo $this->planname['bundle_discount_per_cost'];?>" />
        <input type="hidden" name="bundle_discount_per_setup" id="bundle_discount_per_setup" value="<?php echo $this->planname['bundle_discount_per_setup'];?>" />
        
        <input type="hidden" name="VariableProductCostTotal" id="VariableProductCostTotal" value="<?php echo $this->VariableProductCostTotal;?>" />
        <input type="hidden" name="FixedProductCostTotal" id="FixedProductCostTotal" value="<?php echo $this->FixedProductCostTotal;?>" />
        <input type="hidden" name="VariableProductSetupFeeTotal" id="VariableProductSetupFeeTotal" value="<?php echo $this->VariableProductSetupFeeTotal;?>" />
        <input type="hidden" name="FixedProductSetupFeeTotal" id="FixedProductSetupFeeTotal" value="<?php echo $this->FixedProductSetupFeeTotal; ?>" />
        
        
        <input type="hidden" name="pcost" id="pcost" <?php echo $this->planname['bundle_cost']*0;?> />
        <input type="hidden" name="totalfee" id="totalfee" <?php echo $this->planname['bundle_setup_cost']*0;?> />
        <input type="hidden" name="apid" id="apid" value="0" />
        Plan Price      :</td>
      <?php
	  if($this->planname['bundle_setup_cost']!=0){
	  ?>
      <td align="right" valign="top" class="table-head shadowlight"> <?php echo $currency->toCurrency($this->planname['bundle_setup_cost']);?></td>
      <?php } ?>
      <td align="right" valign="top" nowrap="nowrap" class="table-head shadowlight" id="monthlyfee"><?php echo $currency->toCurrency($this->planname['bundle_cost']);?></td>
    </tr>
      <?php
	  $colspan=2;
	  if($this->planname['bundle_setup_cost']!=0){
		  $colspan=3;
	  ?>
     <tr>
       <td colspan="3" align="right" valign="top" class="normal-text shadowlight">Total Onetime Fee :
        </td>
       <td align="right" valign="top" class="normal-text shadowlight" id="setupfee"> <?php echo $currency->toCurrency($this->planname['bundle_setup_cost']*0);?></td>
     </tr>
     <?php } ?>
     <tr>
       <td colspan="<?php echo  $colspan;?>" align="right" valign="top" class="normal-text shadowlight">Total Monthly Recurring Fee:</td>
       <td align="right" valign="top" class="normal-text shadowlight" id="totalamount"> <?php echo $currency->toCurrency($this->planname['bundle_cost']*0);?></td>
     </tr>
     <tr>
       <td colspan="<?php echo  $colspan;?>" align="right" valign="top" class="normal-text shadowlight"><strong>Gross Amount :</strong></td>
       <td align="right" valign="top" class="normal-text shadowlight b" id="gtotal"> <?php echo $currency->toCurrency(($this->planname['bundle_cost']+$this->planname['bundle_setup_cost'])*0);?></td>
     </tr>

     <tr>
      <?php
		 if($this->planname['bundle_setup_cost']!=0)
		 {
			 $cpan=3;
		 }
		else
		{
			$cpan=2;
		 } ?>
      <td colspan="<?=$cpan;?>" align="right"  class="normal-text b red" nowrap="nowrap" id="provider">
        Please select the  number of providers using this system:<span class="normal-text">
        <select name="provider" id="provider" onchange="updateprice(this.value)">
          <?php 
      for($i=0;$i<=100;$i++)
      {
          echo "<option value=$i>$i</option>";
      }
	  
	 
      ?>
        </select>
        </span></td>
       
      <td align="right" valign="top" >
      <?php
	  if($sess->step=="compare")
	  {
	  ?>
      <input name="checkout" type="submit" disabled="disabled" class="button-disabled" id="checkout" value="Proceed to Payment" />
      <?php
	  }
	  else
	  {
	  ?>
      <input name="checkout" type="submit" disabled="disabled" class="button-disabled" id="checkout" value="Proceed to Registration" />
      <?php
	  }
	  ?>
      </td>
     </tr>
  </table>
  </form>
</div>



