<?php
echo $this->leftmenu(); // Adding admin side Left Side Menu
?>
<script language="javascript" type="text/javascript">
    jQuery(document).ready(function(){
                // binds form submission and fields to the validation engine
                jQuery("#cmsadd").validationEngine();
            });
</script>
<div id="right_panel">
  <form id="cmsadd" name="cmsadd" method="post" action="">
  <input type="hidden" name="id" value="<?php echo $this->PDtd['id']?>"?>
    <table width="100%" border="0" cellspacing="4" cellpadding="4">
      <tr>
        <td colspan="3" class="list-table-header shadow">Edit Paypal Details</td>
      </tr>
      <tr>
        <td class="label line"> Section</td>
        <td>:</td>
        <td class="label line">
        <?php echo $this->PDtd['type'];?>
        </td>
      </tr>
      <tr>
        <td width="19%" class="label line">User Name</td>
        <td width="1%">:</td>
        <td width="80%" class="label line">
        <input name="username" type="text" id="username" size="50" maxlength="250"  class="validate[required]" value="<?php echo $this->PDtd['username'];?>"/></td>
      </tr>
      <tr>
        <td class="label line">Password</td>
        <td>:</td>
        <td class="label line"><input type="password" name="password" id="password" value="<?php echo $this->PDtd['password'];?>" /></td>
      </tr>
      <tr>
        <td class="label line">Signature</td>
        <td>:</td>
        <td class="label line"><label for="listing_order"></label>
        <input type="text" name="signature" id="signature"  size="90" maxlength="250" value="<?php echo $this->PDtd['signature'];?>"/></td>
      </tr>
      <tr>
        <td class="label line">Version</td>
        <td>:</td>
        <td class="label line"><input type="text" name="version" id="version" value="<?php echo $this->PDtd['version'];?>"/></td>
      </tr>
      <tr>
        <td class="label line">Status</td>
        <td>:</td>
        <td class="label line">
          <p>
            <label>
              <input name="status" type="radio" id="status_0" value="1" <?php if($this->PDtd['status']=="1"){echo 'checked="checked"';}?> />
              Active</label>
          
            <label>
              <input type="radio" name="status" value="0" id="status_1"  <?php if($this->PDtd['status']=="0"){echo 'checked="checked"';}?>/>
              Disable</label>
            <br />
        </p></td>
      </tr>
      <tr>
        <td>&nbsp;</td>
        <td>&nbsp;</td>
        <td><input type="submit" name="button" id="button" value="Update" class="shadow" /></td>
      </tr>
    </table>
  </form>
</div>
<div class="clear"></div>
